// Product Details folder import (reports dated 05/07/2026): full per-100g
// nutrition panels, no pack weights. Existing products (matched by slug) get
// price/category/nutrition upgraded; new ones are created with recipes from
// component ingredients. Transcribed from image-based LabelLogic reports.

import type { CatalogueProduct } from "./import-eatpure-products";

export type CatalogueProductV2 = Omit<CatalogueProduct, "packG"> & {
  /** Menu category, from the source report file name. */
  menuCategory:
    | "Bagels"
    | "Baguettes"
    | "Paninis"
    | "Rolls"
    | "Round Labels"
    | "Salads"
    | "Sandwiches"
    | "Specials";
};

const n = (
  kcal: number, kj: number, fat: number, sat: number, carb: number,
  sug: number, fib: number, prot: number, salt: number
): [number, number, number, number, number, number, number, number, number] =>
  [kcal, kj, fat, sat, carb, sug, fib, prot, salt];

export const CATALOGUE_V2: CatalogueProductV2[] = [
  // ---------------- Bagels (Bagels.pdf, 5 products) ----------------
  {
    name: "Cream Cheese and Avocado Bagel",
    description: "Smooth cream cheese with sliced avocado in a soft bagel",
    pricePence: 370, category: "Vegetarian", menuCategory: "Bagels",
    components: ["Plain Bagel", "Cream Cheese", "Avocado"],
    nutrition: n(270, 1140, 7, 2.9, 45, 4.3, 3.2, 9.1, 0.91),
  },
  {
    name: "Luxury Smoked Salmon and Cream Cheese Bagel",
    description: "Smoked Atlantic Salmon with a thick layer of Cream Cheese",
    pricePence: 450, category: "Seafood", menuCategory: "Bagels",
    components: ["Plain Bagel", "Smoked Salmon", "Cream Cheese"],
    nutrition: n(253, 1072, 5.6, 1.4, 42, 3.7, 2.2, 12, 1.3),
  },
  {
    name: "Tuna Avo Bagel",
    description: "Tuna Mayo with Sliced Avocado and crunchy cucumber in a soft bagel",
    pricePence: 529, category: "Seafood", menuCategory: "Bagels",
    components: ["Plain Bagel", "Tuna", "Avocado", "Mayonnaise", "Cucumber", "Salt & Black Pepper"],
    nutrition: n(244, 1033, 6.7, 0.7, 37, 3.3, 2.6, 12, 0.92),
  },
  {
    name: "Brie, Tomato and Basil Bagel",
    description: "Creamy Brie with sliced Tomato and fresh Basil perfectly seasoned in a soft bagel - TRY ME TOASTED",
    pricePence: 529, category: "Vegetarian", menuCategory: "Bagels",
    components: ["Plain Bagel", "Brie", "Tomatoes", "Fresh Basil"],
    nutrition: n(275, 1160, 9, 5.4, 40, 3.6, 2.4, 11, 0.98),
  },
  {
    name: "New York Deli Bagel",
    description: "Sliced Pastrami, Emmental cheese and crunchy gherkins covered with Mustard Mayo in a soft bagel - TRY ME TOASTED",
    pricePence: 549, category: "Red meat", menuCategory: "Bagels",
    components: ["Plain Bagel", "Pastrami", "Emmental", "Gherkins", "Mustard Mayonnaise"],
    nutrition: n(256, 1084, 7, 2.8, 38, 3.4, 2, 13, 1.4),
  },

  // ---------------- Salads (Salads.pdf) ----------------
  {
    name: "Cheese Layered Pasta Salad",
    description: "Mozzarella on a layer of tomato and basil pasta, cucumber, sweetcorn and leaf",
    pricePence: null, category: "Vegetarian", menuCategory: "Salads",
    components: ["White Pasta", "Grated Cheddar", "Tomato & Basil Sauce (chunky)", "Mixed Salad Leaf", "Cucumber", "Sweetcorn"],
    nutrition: n(261, 1095, 13, 7.7, 24, 1.9, 0.4, 13, 0.7),
  },
  {
    name: "Chicken and Bacon Pasta Salad",
    description: "Served with mixed salad of leaf, cucumber, carrot, cherry tomatoes and sweetcorn",
    pricePence: 375, category: "Red meat", menuCategory: "Salads",
    components: ["White Pasta", "Chicken Breast", "Coleslaw", "Cherry Tomatoes", "Mixed Salad Leaf", "Sweetcorn", "Carrot", "Cucumber", "Streaky Bacon", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(130, 543, 7, 1.1, 9.9, 2.6, 0.6, 7.4, 0.66),
  },
  {
    name: "Chicken and Egg Salad",
    description: "Chicken and egg with potatoes, coleslaw and salad",
    pricePence: 550, category: "Chicken", menuCategory: "Salads",
    components: ["Cucumber", "Tomatoes", "Mixed Salad Leaf", "Coleslaw", "Sweetcorn", "New Potatoes", "Cider Honey & Mustard Dressing", "Piri-Piri Seasoning", "Hardboiled Egg", "Chicken Breast", "Salt & Black Pepper"],
    nutrition: n(136, 569, 6.9, 0.8, 13, 7.5, 4.2, 7.3, 1.3),
  },
  {
    name: "Chicken Layered Pasta Salad",
    description: "Sliced Chicken on a layer of pasta pesto, cucumber, sweetcorn and leaf",
    pricePence: null, category: "Chicken", menuCategory: "Salads",
    components: ["White Pasta", "Chicken Breast", "Pesto Basil Paste", "Cucumber", "Sweetcorn", "Mixed Salad Leaf"],
    nutrition: n(188, 795, 4.8, 0.9, 24, 1.5, 0.4, 14, 0.46),
  },
  {
    name: "Chicken Mayo and Bacon Salad",
    description: "Chicken mayo with smoked bacon, potatoes, coleslaw and salad",
    pricePence: 550, category: "Red meat", menuCategory: "Salads",
    components: ["Chicken Breast", "Mayonnaise", "Cucumber", "Tomatoes", "Mixed Salad Leaf", "Coleslaw", "Sweetcorn", "New Potatoes", "Cider Honey & Mustard Dressing", "Piri-Piri Seasoning", "Smoked Streaky Bacon", "Salt & Black Pepper"],
    nutrition: n(200, 832, 13, 1.3, 3.9, 1.8, 1, 17, 1.6),
  },
  {
    name: "Chicken Salad",
    description: "Served with mixed salad of leaf, cucumber, carrot, cherry tomatoes and sweetcorn",
    pricePence: null, category: "Chicken", menuCategory: "Salads",
    components: ["Chicken Breast", "Coleslaw", "Cherry Tomatoes", "Mixed Salad Leaf", "Sweetcorn", "Cucumber"],
    nutrition: n(93, 389, 4.2, 0.6, 3.5, 2.8, 1, 10, 0.64),
  },
  {
    name: "Coronation Chicken Salad",
    description: "Coronation chicken with potatoes, coleslaw and mixed salad",
    pricePence: 550, category: "Chicken", menuCategory: "Salads",
    components: ["Cucumber", "Tomatoes", "Mixed Salad Leaf", "Coleslaw", "Sweetcorn", "New Potatoes", "Cider Honey & Mustard Dressing", "Coronation Chicken", "Chicken Breast", "Piri-Piri Seasoning", "Salt & Black Pepper"],
    nutrition: n(153, 640, 8.7, 0.8, 14, 8.6, 4.2, 6.5, 1.3),
  },
  {
    name: "Ham and Egg Salad",
    description: "Wiltshire ham and free range egg with potatoes, coleslaw and salad",
    pricePence: 550, category: "Red meat", menuCategory: "Salads",
    components: ["Cucumber", "Tomatoes", "Mixed Salad Leaf", "Coleslaw", "Sweetcorn", "New Potatoes", "Cider Honey & Mustard Dressing", "Piri-Piri Seasoning", "Wiltshire Ham", "Hardboiled Egg", "Salt & Black Pepper"],
    nutrition: n(135, 563, 7.1, 0.9, 13, 7.6, 4.2, 6.5, 1.4),
  },
  {
    name: "Piri Piri Chicken Salad",
    description: "Piri piri chicken with potatoes, coleslaw and mixed salad",
    pricePence: 550, category: "Chicken", menuCategory: "Salads",
    components: ["Cucumber", "Tomatoes", "Mixed Salad Leaf", "Coleslaw", "Sweetcorn", "New Potatoes", "Cider Honey & Mustard Dressing", "Piri-Piri Seasoning", "Chicken Breast", "Salt & Black Pepper"],
    nutrition: n(195, 808, 14, 1.7, 12, 7.5, 4.2, 6.3, 1.2),
  },
  {
    name: "Southern Fried Chicken and Sweet Chilli Salad",
    description: "Southern Fried Chicken with Coleslaw on a bed of leaf, Cucumber and Tomato with a Sweet Chilli Dressing",
    pricePence: 425, category: "Chicken", menuCategory: "Salads",
    components: ["Southern Fried Chicken", "Coleslaw", "Mixed Salad Leaf", "Cucumber", "Tomatoes", "Sweet Chilli Dressing", "Mayonnaise"],
    nutrition: n(185, 771, 13, 2.4, 11, 4.8, 0.4, 6.6, 1.1),
  },
  {
    name: "Tuna Crunch Salad",
    description: "Served with mixed salad of leaf, cucumber, carrot, cherry tomatoes and sweetcorn and coleslaw",
    pricePence: 375, category: "Seafood", menuCategory: "Salads",
    components: ["Tuna", "Coleslaw", "Cherry Tomatoes", "Mixed Salad Leaf", "Cucumber", "Sweetcorn", "Carrot", "Mixed Peppers"],
    nutrition: n(70, 294, 2.8, 0.3, 3.6, 2.8, 0.4, 7.8, 0.4),
  },
  {
    name: "Tuna Layered Pasta Salad",
    description: "Tuna Mayo on a layer of Mayo Pasta, cucumber, sweetcorn and leaf",
    pricePence: null, category: "Seafood", menuCategory: "Salads",
    components: ["Tuna", "White Pasta", "Mixed Salad Leaf", "Mayonnaise", "Cucumber", "Sweetcorn", "Salt & Black Pepper"],
    nutrition: n(204, 856, 8.4, 0.8, 20, 1.4, 0.4, 13, 0.53),
  },
  {
    name: "Tuna Mayo Salad",
    description: "Tuna mayo with potatoes, coleslaw and mixed salad",
    pricePence: 550, category: "Seafood", menuCategory: "Salads",
    components: ["Tuna", "Mayonnaise", "Cucumber", "Tomatoes", "Mixed Salad Leaf", "Coleslaw", "Sweetcorn", "New Potatoes", "Cider Honey & Mustard Dressing", "Piri-Piri Seasoning", "Salt & Black Pepper"],
    nutrition: n(207, 862, 14, 1.3, 3, 2, 1, 17, 1.1),
  },
  {
    name: "Wiltshire Ham Salad Bowl",
    description: "Served with Mixed Salad Leaf, Cucumber, Carrot, Cherry Tomatoes, Sweetcorn & Coleslaw",
    pricePence: null, category: "Red meat", menuCategory: "Salads",
    components: ["Wiltshire Ham", "Coleslaw", "Cherry Tomatoes", "Mixed Salad Leaf", "Sweetcorn", "Carrot", "Cucumber"],
    nutrition: n(71, 296, 3.4, 0.5, 4.5, 3.4, 0.6, 5.8, 0.73),
  },

  // ---------------- Paninis / hot items (panini.pdf) ----------------
  {
    name: "All Day Breakfast HOT Wrap",
    description: "Slices of Cumberland sausage, smoked streaky bacon topped with egg mayo and toasted",
    pricePence: 425, category: "Red meat", menuCategory: "Paninis",
    components: ["Tortilla Wrap", "Free Range Eggs", "Cumberland Sausage", "Smoked Streaky Bacon", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(285, 1006, 16, 4.9, 22, 2.8, 1, 12, 0.96),
  },
  {
    name: "All Day Breakfast Panini",
    description: "Slices of Cumberland sausage, smoked streaky bacon topped with egg mayo and toasted",
    pricePence: 520, category: "Red meat", menuCategory: "Paninis",
    components: ["Panini", "Free Range Eggs", "Cumberland Sausage", "Smoked Streaky Bacon", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(256, 907, 12, 3.4, 26, 2.6, 1.5, 12, 1.2),
  },
  {
    name: "BBQ Chicken & Cheese Panini",
    description: "Chicken Breast with BBQ Sauce and Mature Cheddar - Ready for Toasting",
    pricePence: 350, category: "Chicken", menuCategory: "Paninis",
    components: ["Panini", "Chicken Breast", "Mature Cheddar", "BBQ Sauce"],
    nutrition: n(251, 1050, 7.5, 4.2, 31, 2.3, 1.7, 16, 1.1),
  },
  {
    name: "Brie & Cranberry Panini",
    description: "Creamy Brie and Cranberry Sauce - Enjoy me Toasted!",
    pricePence: 340, category: "Vegetarian", menuCategory: "Paninis",
    components: ["Panini", "Brie", "Cranberry Sauce"],
    nutrition: null,
  },
  {
    name: "Cheddar Cheese Panini",
    description: "Sliced Mild Cheddar in a Panini",
    pricePence: 300, category: "Vegetarian", menuCategory: "Paninis",
    components: ["Panini", "Sliced Mild Cheddar"],
    nutrition: null,
  },
  {
    name: "Cheddar Cheese & Mushroom Panini",
    description: "Sliced Mild Cheddar with Sliced Mushrooms",
    pricePence: 340, category: "Vegetarian", menuCategory: "Paninis",
    components: ["Panini", "Sliced Mild Cheddar", "Sliced Mushrooms"],
    nutrition: null,
  },
  {
    name: "Cheddar Cheese Toastie",
    description: "Sliced Cheddar cheese on white bread",
    pricePence: null, category: "Vegetarian", menuCategory: "Paninis",
    components: ["White Bread", "Sliced Mild Cheddar"],
    nutrition: n(295, 1245, 14, 7.6, 30, 1.8, 1.8, 15, 1.4),
  },
  {
    name: "Chicken Fajita Hot Wrap",
    description: "Chicken slices with onion and pepper in a fajita seasoning topped with cheese",
    pricePence: 450, category: "Chicken", menuCategory: "Paninis",
    components: ["Tortilla Wrap", "Chicken Breast", "Mature Cheddar", "White Onion", "Diced Red Peppers", "Fajita Seasoning"],
    nutrition: n(241, 1013, 9.7, 5.3, 24, 1.8, 1.8, 16, 2.2),
  },
  {
    name: "Chicken, Pesto and Mozzarella Panini",
    description: "Sliced Chicken with Green Pesto, Spinach and topped with Creamy Mozzarella",
    pricePence: 550, category: "Chicken", menuCategory: "Paninis",
    components: ["Panini", "Chicken Breast", "Mozzarella", "Green Pesto", "Baby Spinach"],
    nutrition: n(225, 945, 7.4, 3.3, 21, 0.6, 2.5, 15, 1.1),
  },
  {
    name: "Ham, Brie and Honey Panini",
    description: "Creamy Brie, Ham drizzled with Honey - Enjoy me Toasted!",
    pricePence: 380, category: "Red meat", menuCategory: "Paninis",
    components: ["Panini", "Brie", "Sliced Cooked Ham", "Honey"],
    nutrition: n(234, 979, 7, 0.2, 33, 5, 1.7, 12, 1.4),
  },
  {
    name: "Jerk Chicken and Cheese Panini",
    description: "Chicken Breast, Reggae Reggae Jerk Sauce & Cheddar",
    pricePence: 330, category: "Chicken", menuCategory: "Paninis",
    components: ["Panini", "Chicken Breast", "Mature Cheddar", "Jerk Peri Peri Sauce"],
    nutrition: n(242, 1013, 7.4, 4.1, 30, 1.6, 1.6, 16, 1),
  },
  {
    name: "Margherita Bagel",
    description: "Soft Bagel with Tomato & Basil Sauce and Mature Cheddar Cheese",
    pricePence: 360, category: "Vegetarian", menuCategory: "Bagels",
    components: ["Plain Bagel", "Mature Cheddar", "Tomato & Basil Sauce"],
    nutrition: n(309, 1300, 12, 6.4, 39, 3.4, 2.1, 14, 1.2),
  },
  {
    name: "Mushroom & Cheese Toastie",
    description: "Chestnut mushrooms with slices of emmental cheese, béchamel sauce and dijon mustard",
    pricePence: 300, category: "Vegetarian", menuCategory: "Paninis",
    components: ["White Bloomer", "Sliced Mushrooms", "Emmental", "Bechamel Sauce", "Dijon Mustard"],
    nutrition: n(273, 1148, 10, 6.2, 26, 5.7, 3.6, 19, 1.2),
  },
  {
    name: "Peri Peri Chicken and Cheese Panini",
    description: "Panini with Sliced Chicken and Cheddar Cheese with a Peri-Peri sauce",
    pricePence: 320, category: "Chicken", menuCategory: "Paninis",
    components: ["Panini", "Chicken Breast", "Mature Cheddar", "Jerk Peri Peri Sauce"],
    nutrition: n(241, 1009, 7.3, 4.1, 30, 1.6, 1.6, 16, 1),
  },
  {
    name: "Sausage & Bacon Panini",
    description: "Slices of Cumberland sausage and smoked streaky bacon",
    pricePence: 520, category: "Red meat", menuCategory: "Paninis",
    components: ["Panini", "Cumberland Sausage", "Smoked Streaky Bacon"],
    nutrition: n(268, 822, 11, 3.7, 33, 3.7, 1.8, 12, 1.4),
  },
  {
    name: "Sausage, Cheese and Onion Panini",
    description: "Slices of Cumberland sausage with Red Onion and Cheddar slices",
    pricePence: 430, category: "Red meat", menuCategory: "Paninis",
    components: ["Panini", "Cumberland Sausage", "Sliced Mild Cheddar", "Red Onion"],
    nutrition: n(261, 820, 11, 5, 31, 3.6, 1.8, 12, 1.3),
  },
  {
    name: "VEGAN Margherita Panini",
    description: "Panini with Tomato & Basil Sauce and Vegan Cheese",
    pricePence: 400, category: "Vegetarian", menuCategory: "Paninis",
    components: ["Panini", "Vegan Cheddar Slices", "Tomato & Basil Sauce"],
    nutrition: n(253, 1056, 7.4, 6, 43, 2.2, 2.2, 5.9, 1.3),
  },
  // Price updates for existing products seen in panini.pdf (runner updates in place):
  {
    name: "Brie, Bacon and Cranberry Panini",
    description: "Creamy Brie, with Bacon and Cranberry sauce - Enjoy me Toasted!",
    pricePence: 420, category: "Red meat", menuCategory: "Paninis",
    components: ["Panini", "Brie", "Streaky Bacon", "Cranberry Sauce"],
    nutrition: n(265, 1105, 10, 1.1, 34, 3.6, 1.8, 12, 1.3),
  },
  {
    name: "Cheese & Tomato Panini",
    description: "Mature Cheddar Cheese with Sliced Tomatoes",
    pricePence: 290, category: "Vegetarian", menuCategory: "Paninis",
    components: ["Panini", "Mature Cheddar", "Tomatoes"],
    nutrition: n(275, 1149, 10, 5.9, 36, 2.1, 2, 12, 1.3),
  },
  {
    name: "Chicken, Chorizo & Cheese Panini",
    description: "100% Chicken breast, with slices of Chorizo and Mature Cheddar Cheese",
    pricePence: 340, category: "Chicken", menuCategory: "Paninis",
    components: ["Panini", "Chicken Breast", "Mature Cheddar", "Chorizo"],
    nutrition: n(255, 1064, 7.8, 4.4, 31, 1.7, 1.7, 17, 1.1),
  },
  {
    name: "Ham & Cheese Panini",
    description: "Wiltshire Ham & Mature Cheddar - perfect toasted",
    pricePence: 350, category: "Red meat", menuCategory: "Paninis",
    components: ["Panini", "Wiltshire Ham", "Mature Cheddar"],
    nutrition: n(249, 1037, 8.1, 4.5, 32, 1.9, 1.8, 14, 1.5),
  },
  {
    name: "Ham & Cheese Toastie",
    description: "Wiltshire Ham & Mature Cheddar - perfect toasted",
    pricePence: 300, category: "Red meat", menuCategory: "Paninis",
    components: ["White Bread", "Mature Cheddar", "Wiltshire Ham", "Sunflower Spread"],
    nutrition: n(263, 1101, 13, 7.2, 20, 1.5, 1.2, 16, 1.5),
  },
  {
    name: "Ham and Cheese Ciabatta",
    description: "Wiltshire Ham & Mature Cheddar with mustard mayo - perfect toasted",
    pricePence: 420, category: "Red meat", menuCategory: "Paninis",
    components: ["Ciabatta Roll", "Wiltshire Ham", "Mature Cheddar", "Mayonnaise", "Dijon Mustard"],
    nutrition: n(286, 1198, 14, 4.8, 25, 3.3, 2, 13, 1.3),
  },
  {
    name: "Hunters Chicken Ciabatta",
    description: "Sliced Chicken and Bacon covered in Cheddar with a BBQ sauce",
    pricePence: 420, category: "Chicken", menuCategory: "Paninis",
    components: ["Ciabatta Roll", "Chicken Breast", "Mature Cheddar", "Streaky Bacon", "BBQ Sauce (smoky)"],
    nutrition: n(258, 1084, 11, 4.8, 23, 4.1, 1.6, 17, 1),
  },
  {
    name: "Margherita Panini",
    description: "Panini with Tomato & Basil Sauce and Cheddar Cheese",
    pricePence: 320, category: "Vegetarian", menuCategory: "Paninis",
    components: ["Panini", "Mature Cheddar", "Tomato & Basil Sauce"],
    nutrition: n(284, 1184, 10, 6.1, 37, 2.1, 2, 13, 1.3),
  },
  {
    name: "Piri Piri Chicken with Sweet Chilli sauce and Cheese Panini",
    description: "Piri Piri Chicken with Sweet Chilli sauce and Cheese in a Panini",
    pricePence: 430, category: "Chicken", menuCategory: "Paninis",
    components: ["Panini", "Mature Cheddar", "Chicken Breast", "Sweet Chilli Sauce", "Piri-Piri Seasoning"],
    nutrition: n(263, 1097, 9.2, 4.3, 32, 3.1, 2.1, 15, 1.4),
  },
  {
    name: "Southern Fried Chicken and Bacon Hot Wrap",
    description: "Southern Fried Chicken Fillet, Bacon, Cheese & BBQ Sauce",
    pricePence: 320, category: "Chicken", menuCategory: "Paninis",
    components: ["Tortilla Wrap", "Southern Fried Chicken", "Mature Cheddar", "Streaky Bacon", "BBQ Sauce"],
    nutrition: n(295, 1235, 14, 7.2, 29, 2.5, 1.6, 14, 1.8),
  },
  {
    name: "Tuna Melt Ciabatta",
    description: "Tuna Mayonnaise & Mature Cheddar - ready for toasting",
    pricePence: 380, category: "Seafood", menuCategory: "Paninis",
    components: ["Ciabatta Roll", "Mature Cheddar", "Tuna", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(280, 1178, 12, 4.9, 27, 3.3, 2, 14, 0.88),
  },
  {
    name: "Tuna Melt Panini",
    description: "Tuna Mayonnaise & Mature Cheddar - ready for toasting",
    pricePence: 350, category: "Seafood", menuCategory: "Paninis",
    components: ["Panini", "Mature Cheddar", "Tuna", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(270, 1125, 11, 4.5, 31, 1.8, 1.7, 14, 1.3),
  },
  {
    name: "Tuna Cheddar Toastie",
    description: "Tuna Mayo with spring onions and red peppers, covered in Sliced Cheddar on Malted Bloomer - Perfect Toasted",
    pricePence: 440, category: "Seafood", menuCategory: "Paninis",
    components: ["Malted Bloomer", "Tuna Mayonnaise", "Sliced Mild Cheddar", "Diced Red Peppers", "Spring Onions"],
    nutrition: n(252, 1058, 11, 5.1, 23, 1.1, 2.2, 14, 1.3),
  },

  // ---------------- Baguettes (Baguettes.pdf, 19 products) ----------------
  {
    name: "BLT with Mayo Baguette",
    description: "Bacon, Lettuce & Tomato with Mayonnaise in a Multigrain Baguette",
    pricePence: 450, category: "Red meat", menuCategory: "Baguettes",
    components: ["Streaky Bacon", "Lettuce", "Tomatoes", "Mayonnaise (egg powder recipe)", "White Baguette", "Multigrain Baguette"],
    nutrition: n(257, 1065, 19, 5.1, 2.3, 0.8, 0.4, 13, 2.1),
  },
  {
    name: "Cheese and Coleslaw Baguette",
    description: "Sliced Mild Cheddar with Coleslaw",
    pricePence: 450, category: "Vegetarian", menuCategory: "Baguettes",
    components: ["Sliced Mild Cheddar", "Coleslaw", "Sunflower Spread", "White Baguette", "Multigrain Baguette"],
    nutrition: n(343, 1431, 29, 15, 2.4, 1.3, 0.4, 18, 1.8),
  },
  {
    name: "Cheese and Onion Baguette",
    description: "Sliced Mild Cheddar with Red Onion",
    pricePence: 450, category: "Vegetarian", menuCategory: "Baguettes",
    components: ["Sliced Mild Cheddar", "Red Onion", "Sunflower Spread", "White Baguette", "Multigrain Baguette"],
    nutrition: n(299, 1246, 19, 6.3, 24, 1.9, 1.9, 9.4, 1.1),
  },
  {
    name: "Cheese and Pickle Baguette",
    description: "Sliced Mild Cheddar with Branston Sweet Pickle",
    pricePence: 450, category: "Vegetarian", menuCategory: "Baguettes",
    components: ["Sliced Mild Cheddar", "Branston Sweet Pickle", "Sunflower Spread", "White Baguette", "Multigrain Baguette"],
    nutrition: n(353, 1470, 28, 15, 7.9, 5.7, 0.4, 18, 2.3),
  },
  {
    name: "Cheese Ploughman's Baguette",
    description: "Mature Cheddar with Sweet Pickle, Mayo and salad",
    pricePence: 450, category: "Vegetarian", menuCategory: "Baguettes",
    components: ["White Baguette", "Mature Cheddar", "Mayonnaise (egg powder recipe)", "Branston Sweet Pickle", "Red Onion", "Sunflower Spread", "Cucumber", "Tomatoes", "Mixed Salad Leaf"],
    nutrition: n(276, 1155, 12, 5.3, 30, 2.3, 1.5, 10, 1.4),
  },
  {
    name: "Chicken Mayo and Sweetcorn Baguette",
    description: "100% Chicken Breast with mayonnaise and sweetcorn",
    pricePence: 450, category: "Chicken", menuCategory: "Baguettes",
    components: ["Chicken Breast", "Mayonnaise", "Sweetcorn", "Sunflower Spread", "Multigrain Baguette", "Salt & Black Pepper"],
    nutrition: n(199, 830, 13, 1.3, 4.3, 1.3, 0.7, 17, 1.4),
  },
  {
    name: "Chicken Mayo with BBQ Sauce, Cucumber and Leaf Baguette",
    description: "100% Chicken Breast with mayonnaise, BBQ Sauce and Leaf",
    pricePence: 450, category: "Chicken", menuCategory: "Baguettes",
    components: ["White Baguette", "Chicken Breast", "Mayonnaise", "Mixed Salad Leaf", "BBQ Sauce", "Cucumber"],
    nutrition: n(184, 770, 11, 1, 5.3, 2.7, 0.4, 16, 1.4),
  },
  {
    name: "Chicken Mayo, Bacon and Lettuce Baguette",
    description: "Chicken Breast, Bacon and Lettuce with Mayonnaise",
    pricePence: 450, category: "Red meat", menuCategory: "Baguettes",
    components: ["Chicken Breast", "Mayonnaise", "Sunflower Spread", "White Baguette", "Streaky Bacon", "Mixed Salad Leaf", "Multigrain Baguette", "Salt & Black Pepper"],
    nutrition: n(213, 889, 14, 1.5, 3.4, 0.6, 0.4, 19, 1.6),
  },
  {
    name: "Chicken Mayo, Chorizo and Leaf Baguette",
    description: "100% Chicken Breast, Chorizo, Leaf and Mayonnaise",
    pricePence: 450, category: "Red meat", menuCategory: "Baguettes",
    components: ["Chicken Breast", "Chorizo", "Mixed Salad Leaf", "Mayonnaise", "Sunflower Spread", "Multigrain Baguette"],
    nutrition: n(237, 988, 17, 4, 3.2, 1.1, 0.4, 18, 1.9),
  },
  {
    name: "Chicken Piri Piri and Sweet Chilli Baguette",
    description: "Piri Piri Chicken with Mayo, Sweet Chilli, Tomato and leaf",
    pricePence: 450, category: "Chicken", menuCategory: "Baguettes",
    components: ["Sunflower Spread", "White Baguette", "Tomatoes", "Mixed Salad Leaf", "Sweet Chilli Sauce", "Piri-Piri Seasoning", "Chicken Breast", "Mayonnaise (egg powder recipe)", "Multigrain Baguette"],
    nutrition: n(317, 1314, 22, 3.2, 18, 7.1, 2.9, 5.9, 2.1),
  },
  {
    name: "Egg Mayo and Bacon Baguette",
    description: "Free range egg mayo with streaky bacon",
    pricePence: 450, category: "Red meat", menuCategory: "Baguettes",
    components: ["Free Range Eggs", "Streaky Bacon", "Mayonnaise", "Sunflower Spread", "White Baguette", "Multigrain Baguette"],
    nutrition: n(254, 1052, 21, 5, 1.2, 0.4, 0.4, 15, 1.6),
  },
  {
    name: "Egg Mayo and Cress Baguette",
    description: "Free range egg mayo with cress",
    pricePence: 450, category: "Vegetarian", menuCategory: "Baguettes",
    components: ["Multigrain Baguette", "Free Range Eggs", "Sunflower Spread", "Cress", "Mayonnaise", "White Baguette", "Salt & Black Pepper"],
    nutrition: n(276, 1148, 13, 2.1, 30, 0.7, 2.3, 10, 1),
  },
  {
    name: "Ham and Cheese Baguette",
    description: "Wiltshire Ham and Mature Cheddar",
    pricePence: 450, category: "Red meat", menuCategory: "Baguettes",
    components: ["Wiltshire Ham", "Mature Cheddar", "Sunflower Spread", "White Baguette", "Multigrain Baguette"],
    nutrition: n(268, 1114, 20, 10, 1.4, 0.6, 0.4, 20, 1.9),
  },
  {
    name: "Ham and Coleslaw Baguette",
    description: "Wiltshire Ham with Coleslaw",
    pricePence: 450, category: "Red meat", menuCategory: "Baguettes",
    components: ["Coleslaw", "Sunflower Spread", "Wiltshire Ham", "Multigrain Baguette", "White Baguette"],
    nutrition: n(255, 1066, 15, 2.7, 23, 2.3, 1.8, 7.9, 1.4),
  },
  {
    name: "Ham Salad Baguette",
    description: "Sliced Cooked Ham with cucumber, tomato and leaf",
    pricePence: 450, category: "Red meat", menuCategory: "Baguettes",
    components: ["Sliced Cooked Ham", "Cucumber", "Tomatoes", "Mixed Salad Leaf", "Sunflower Spread", "White Baguette", "Multigrain Baguette"],
    nutrition: n(90, 376, 4.7, 1, 2.3, 1.1, 0.6, 9.7, 1.2),
  },
  {
    name: "Tuna Mayo and Cucumber Baguette",
    description: "Tuna Mayo with Cucumber",
    pricePence: 450, category: "Seafood", menuCategory: "Baguettes",
    components: ["Tuna", "Cucumber", "Mayonnaise", "Sunflower Spread", "Multigrain Baguette", "White Baguette", "Salt & Black Pepper"],
    nutrition: n(208, 864, 16, 2.1, 1.7, 0.6, 0.4, 13, 0.86),
  },
  {
    name: "Tuna Mayo and Salad Baguette",
    description: "Tuna Mayo with cucumber, tomato and leaf",
    pricePence: 450, category: "Seafood", menuCategory: "Baguettes",
    components: ["Tuna", "Sunflower Spread", "Cucumber", "Tomatoes", "Mixed Salad Leaf", "Mayonnaise", "White Baguette", "Multigrain Baguette", "Salt & Black Pepper"],
    nutrition: n(185, 769, 15, 2, 2, 0.9, 0.4, 11, 0.75),
  },
  {
    name: "Tuna Mayo and Sweetcorn Baguette",
    description: "Tuna Mayo with Sweetcorn",
    pricePence: 450, category: "Seafood", menuCategory: "Baguettes",
    components: ["Tuna", "Sweetcorn", "Sunflower Spread", "Mayonnaise", "Multigrain Baguette", "White Baguette", "Salt & Black Pepper"],
    nutrition: n(222, 920, 17, 2.2, 4.9, 2.1, 0.9, 13, 0.83),
  },
  {
    name: "Tuna Mayo, Tomato and Red Onion Baguette",
    description: "Tuna Mayo with Tomato and Red Onion",
    pricePence: 450, category: "Seafood", menuCategory: "Baguettes",
    components: ["Tuna", "Red Onion", "Sunflower Spread", "Mayonnaise", "Tomatoes", "Multigrain Baguette", "White Baguette", "Salt & Black Pepper"],
    nutrition: n(211, 876, 16, 2.2, 4, 1.8, 0.7, 13, 0.82),
  },

  // ---------------- Round Labels (deli pots & snacks) ----------------
  {
    name: "Chicken Chunks",
    description: "Homemade Chicken Chunks in Breadcrumbs",
    pricePence: 210, category: "Chicken", menuCategory: "Round Labels",
    components: ["Chicken Breast", "Golden Breadcrumbs", "Free Range Eggs", "Semi Skimmed Milk"],
    nutrition: n(209, 878, 2.1, 0.5, 23, 1.9, 0.4, 26, 0.93),
  },
  {
    name: "Crudites & Hummus",
    description: "Carrot, Cucumber & Celery Batons",
    pricePence: 190, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Hummus", "Carrot", "Cucumber", "Celery Batons"],
    nutrition: null,
  },
  {
    name: "Festive Chicken Chunks",
    description: "Homemade Chicken Chunks coated in Breaded Sage & Onion Stuffing with cranberry dip",
    pricePence: 240, category: "Chicken", menuCategory: "Round Labels",
    components: ["Chicken Breast", "Sage & Onion Breadcrumb Coating", "Cranberry Sauce", "Semi Skimmed Milk", "Free Range Eggs"],
    nutrition: null,
  },
  {
    name: "Fruit Salad",
    description: "Fresh Seasonal Fruit",
    pricePence: null, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Strawberries", "Pineapple", "Grapes", "Melon"],
    nutrition: null,
  },
  {
    name: "Greek Yoghurt, Granola and Honey",
    description: "Half fat Greek Yoghurt with a dash of honey and Granola to top",
    pricePence: null, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Greek Yogurt", "Granola", "Honey"],
    nutrition: null,
  },
  {
    name: "Greek Yoghurt, Lemon and Granola",
    description: "Half fat Greek Yoghurt, Lemon curd and Granola topping",
    pricePence: null, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Greek Yogurt", "Lemon Curd", "Granola"],
    nutrition: null,
  },
  {
    name: "Greek Yoghurt, Strawberry and Granola",
    description: "Half fat Greek Yoghurt, Strawberry Compote and Granola topping",
    pricePence: null, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Greek Yogurt", "Strawberry Compote", "Granola"],
    nutrition: null,
  },
  {
    name: "Indian Snack Pot",
    description: "Onion Bhaji, Veg Samosa, Saag Aloo Pakora with Mango Chutney",
    pricePence: 180, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Indian Snacks Selection", "Mango Chutney"],
    nutrition: null,
  },
  {
    name: "Noodle Salad",
    description: null,
    pricePence: 350, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Noodles"],
    nutrition: null,
  },
  {
    name: "Pasta Salad",
    description: null,
    pricePence: 250, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["White Pasta"],
    nutrition: null,
  },
  {
    name: "Plain Salad",
    description: "Lettuce, cucumber, Cherry Tomatoes and Carrot",
    pricePence: 100, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Cucumber", "Cherry Tomatoes", "Carrot", "Mixed Salad Leaf"],
    nutrition: null,
  },
  {
    name: "Prawn Mayo Topping Pot",
    description: "Prawns in Mayonnaise",
    pricePence: 130, category: "Seafood", menuCategory: "Round Labels",
    components: ["Prawns", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: null,
  },
  {
    name: "Salad Pot",
    description: "Mixed salad",
    pricePence: 350, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Mixed Salad Leaf", "Cucumber", "Cherry Tomatoes", "Carrot"],
    nutrition: null,
  },
  {
    name: "Topping Pot - Cheese",
    description: "Mild grated cheddar, mozzarella and Red Leicester",
    pricePence: 130, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Grated Cheddar", "Grated Mozzarella & Cheddar", "Red Leicester"],
    nutrition: n(415, 1719, 35, 21, 1, 0.4, 0.4, 25, 1.8),
  },
  {
    name: "Topping Pot - Cheese & Beans",
    description: "Grated cheese with baked beans",
    pricePence: 130, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Grated Cheddar", "Baked Beans"],
    nutrition: null,
  },
  {
    name: "Topping Pot - Chicken & Bacon Mayo Mix",
    description: "Chicken breast and bacon in mayonnaise",
    pricePence: 130, category: "Red meat", menuCategory: "Round Labels",
    components: ["Chicken Breast", "Mayonnaise", "Streaky Bacon", "Salt & Black Pepper"],
    nutrition: null,
  },
  {
    name: "Topping Pot - Coleslaw",
    description: "Fresh coleslaw",
    pricePence: null, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Coleslaw (fresh)"],
    nutrition: n(253, 1041, 26, 2, 3.5, 2.7, 0.4, 0.6, 1.4),
  },
  {
    name: "Topping Pot - Tuna",
    description: "Tuna mayonnaise",
    pricePence: 130, category: "Seafood", menuCategory: "Round Labels",
    components: ["Tuna", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: null,
  },
  {
    name: "Tuna Mayo & Cucumber Pot",
    description: "Tuna mayo with cucumber",
    pricePence: null, category: "Seafood", menuCategory: "Round Labels",
    components: ["Tuna", "Mayonnaise", "Cucumber"],
    nutrition: null,
  },
  {
    name: "Tuna Mayo & Cucumber Pot - GLUTEN FREE",
    description: "Tuna mayo with cucumber (gluten free)",
    pricePence: null, category: "Seafood", menuCategory: "Round Labels",
    components: ["Tuna", "Mayonnaise", "Cucumber"],
    nutrition: null,
  },
  {
    name: "Tuna Mayo & Sweetcorn Pot",
    description: "Tuna mayo with sweetcorn",
    pricePence: null, category: "Seafood", menuCategory: "Round Labels",
    components: ["Tuna", "Mayonnaise", "Sweetcorn"],
    nutrition: null,
  },
  {
    name: "Tuna Mayo & Sweetcorn Pot - GLUTEN FREE",
    description: "Tuna mayo with sweetcorn (gluten free)",
    pricePence: null, category: "Seafood", menuCategory: "Round Labels",
    components: ["Tuna", "Mayonnaise", "Sweetcorn"],
    nutrition: null,
  },
  {
    name: "White Chocolate & Cranberry Cookie",
    description: "Homemade cookies with White Choc Chunks & Cranberries",
    pricePence: 140, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["White Chocolate & Cranberry Cookie Mix"],
    nutrition: null,
  },
  {
    name: "Winter Veg Soup",
    description: "Carrot, Sweet Potato & Potato",
    pricePence: null, category: "Vegetarian", menuCategory: "Round Labels",
    components: ["Carrot", "Sweet Potato", "New Potatoes"],
    nutrition: null,
  },

  // ---------------- Specials (Specials.pdf) ----------------
  {
    name: "*SPECIAL* Beef, Emmental and Caramelised Onion Bloomer",
    description: "Beef, Emmental cheese, and caramelised red onion chutney with leaf on thick malted bloomer",
    pricePence: 380, category: "Red meat", menuCategory: "Specials",
    components: ["Malted Bloomer", "Emmental", "Sliced Roast Beef", "Caramelised Onion Chutney", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(242, 1020, 8.5, 4.4, 27, 5.5, 2.1, 13, 1.2),
  },
  {
    name: "*SPECIAL* Chilli Prawn on White Bread",
    description: "Prawns in a tomato, garlic, and mild chilli sauce with leaf on white bread",
    pricePence: 350, category: "Seafood", menuCategory: "Specials",
    components: ["White Bread", "Prawns", "Tomato & Chilli Sauce", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(177, 749, 3.4, 0.4, 29, 3.5, 2, 9.3, 1.2),
  },
  {
    name: "*VEGAN SPECIAL* BBQ Jackfruit Wrap",
    description: "BBQ jackfruit wrap with leaf, cucumber, and sweetcorn",
    pricePence: 380, category: "Vegetarian", menuCategory: "Specials",
    components: ["Tortilla Wrap", "BBQ Jackfruit", "Red Onion", "Sweetcorn", "Mixed Salad Leaf", "Cucumber"],
    nutrition: n(168, 708, 3.4, 1.2, 30, 7.2, 1.6, 4.2, 0.95),
  },
  {
    name: "Beef Salad Baguette",
    description: "Sliced Beef with Salad on White Baguette",
    pricePence: 400, category: "Red meat", menuCategory: "Specials",
    components: ["White Baguette", "Sliced Roast Beef", "Tomatoes", "Mixed Salad Leaf", "Sunflower Spread", "Cucumber"],
    nutrition: n(179, 756, 2.7, 0.5, 30, 1.8, 1.6, 9.4, 1.1),
  },
  {
    name: "BLT Baguette",
    description: "Bacon, Lettuce and Tomato on White Baguette",
    pricePence: 400, category: "Red meat", menuCategory: "Specials",
    components: ["White Baguette", "Smoked Streaky Bacon", "Tomatoes", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(257, 1079, 11, 3.3, 29, 1.6, 1.4, 13, 1.3),
  },
  {
    name: "Brie Baguette",
    description: "Sliced Brie with cranberry sauce and leaf on a white baguette",
    pricePence: 400, category: "Vegetarian", menuCategory: "Specials",
    components: ["White Baguette", "Brie", "Mixed Salad Leaf", "Cranberry Sauce", "Sunflower Spread"],
    nutrition: n(281, 1178, 13, 8.5, 28, 2.6, 1.7, 11, 1.2),
  },
  {
    name: "Butternut Squash and Sweet Potato Soup with White Bap and Butter",
    description: "Butternut squash and sweet potato soup served with a white bap and butter portion",
    pricePence: null, category: "Vegetarian", menuCategory: "Specials",
    components: ["New Potatoes", "Butternut Squash", "Sweet Potato", "Vegetable Bouillon", "White Roll", "Butter", "Salt & Black Pepper"],
    nutrition: null,
  },
  {
    name: "Carrot and Coriander Soup with White Bap and Butter",
    description: "Carrot and coriander soup served with a white bap and butter portion",
    pricePence: null, category: "Vegetarian", menuCategory: "Specials",
    components: ["New Potatoes", "Carrot", "Fresh Coriander", "Vegetable Bouillon", "White Roll", "Butter", "Salt & Black Pepper"],
    nutrition: null,
  },
  {
    name: "Cheese and Coleslaw Baguette (White)",
    description: "Grated Cheese with creamy coleslaw on White Baguette",
    pricePence: 400, category: "Vegetarian", menuCategory: "Specials",
    components: ["White Baguette", "Grated Cheddar", "Coleslaw", "Sunflower Spread"],
    nutrition: n(242, 1018, 8.9, 4.2, 31, 1.8, 1.6, 9.7, 1.4),
  },
  {
    name: "Cheese Salad Baguette",
    description: "Sliced Cheddar Cheese with salad on white baguette",
    pricePence: 400, category: "Vegetarian", menuCategory: "Specials",
    components: ["White Baguette", "Mature Cheddar", "Tomatoes", "Sunflower Spread", "Cucumber", "Mixed Salad Leaf"],
    nutrition: n(290, 1213, 14, 8.1, 26, 0.8, 1.3, 13, 1.4),
  },
  {
    name: "Cheese Savoury Baguette",
    description: "Cheese Savoury on Multigrain Baguette",
    pricePence: 400, category: "Vegetarian", menuCategory: "Specials",
    components: ["Multigrain Baguette", "Cheese Savoury Mix", "Carrot", "Red Onion", "Sunflower Spread"],
    nutrition: n(350, 1432, 19, 4, 33, 1.3, 2.7, 10, 1.3),
  },
  {
    name: "Chicken and Sweetcorn Soup with White Bap and Butter",
    description: "Chicken and sweetcorn soup served with a white bap and butter portion",
    pricePence: null, category: "Chicken", menuCategory: "Specials",
    components: ["Chicken Breast", "Sweetcorn", "New Potatoes", "Vegetable Bouillon", "White Roll", "Butter", "Salt & Black Pepper"],
    nutrition: null,
  },
  {
    name: "Chicken Mayo with Chorizo Baguette",
    description: "Creamy Chicken Mayo with Sliced Chorizo and leaf on Multigrain Baguette",
    pricePence: 400, category: "Red meat", menuCategory: "Specials",
    components: ["Multigrain Baguette", "Chicken Breast", "Mayonnaise (egg powder recipe)", "Chorizo", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(317, 1318, 17, 2.3, 29, 1.1, 2.1, 13, 1.3),
  },
  {
    name: "Chicken Sweetcorn Baguette",
    description: "Chicken Mayo with Sweetcorn on multigrain Baguette",
    pricePence: 400, category: "Chicken", menuCategory: "Specials",
    components: ["Multigrain Baguette", "Chicken Breast", "Mayonnaise (egg powder recipe)", "Sweetcorn", "Sunflower Spread"],
    nutrition: n(309, 1285, 16, 1.5, 30, 1.4, 2.4, 12, 1.1),
  },
  {
    name: "Chilli Pot with White Bap and Butter",
    description: "Chilli con carne pot served with a white bap and butter portion",
    pricePence: null, category: "Red meat", menuCategory: "Specials",
    components: ["Chilli Con Carne", "White Roll", "Butter"],
    nutrition: null,
  },
  {
    name: "Coronation Chicken Baguette",
    description: "Coronation Chicken on White Baguette",
    pricePence: 400, category: "Chicken", menuCategory: "Specials",
    components: ["White Baguette", "Chicken Breast", "Mayonnaise", "Curry Powder", "Raisins", "Sunflower Spread"],
    nutrition: n(286, 1197, 14, 1.5, 29, 2.4, 1.4, 11, 0.76),
  },
  {
    name: "Egg Salad Baguette",
    description: "Sliced Egg with salad on white Baguette",
    pricePence: 400, category: "Vegetarian", menuCategory: "Specials",
    components: ["White Baguette", "Free Range Eggs", "Tomatoes", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(182, 766, 4.8, 1.1, 26, 1.3, 1.3, 9.2, 0.72),
  },
  {
    name: "Jacket Potato with Cheese",
    description: "Baked jacket potato with grated cheddar",
    pricePence: null, category: "Vegetarian", menuCategory: "Specials",
    components: ["Baked Jacket Potato", "Grated Cheddar"],
    nutrition: null,
  },
  {
    name: "Jacket Potato with Chicken Mayo",
    description: "Baked jacket potato with chicken mayo",
    pricePence: null, category: "Chicken", menuCategory: "Specials",
    components: ["Baked Jacket Potato", "Chicken Breast", "Mayonnaise (egg powder recipe)"],
    nutrition: null,
  },
  {
    name: "Jacket Potato with Tuna Mayo",
    description: "Baked jacket potato with tuna mayo",
    pricePence: null, category: "Seafood", menuCategory: "Specials",
    components: ["Baked Jacket Potato", "Tuna Mayonnaise"],
    nutrition: null,
  },
  {
    name: "Potato and Leek Soup with White Bap and Butter",
    description: "Potato and leek soup served with a white bap and butter portion",
    pricePence: null, category: "Vegetarian", menuCategory: "Specials",
    components: ["New Potatoes", "Leeks", "Vegetable Bouillon", "White Roll", "Butter", "Salt & Black Pepper"],
    nutrition: null,
  },
  {
    name: "Sausage, Caramelised Onion & Cheddar",
    description: "Cumberland sausage with caramelised onion and cheddar",
    pricePence: 380, category: "Red meat", menuCategory: "Specials",
    components: ["Malted Bloomer", "Cumberland Sausage (butcher's)", "Sliced Mild Cheddar", "Caramelised Onion Chutney", "Sunflower Spread"],
    nutrition: n(288, 1206, 15, 5.5, 26, 5.6, 1.8, 11, 1.3),
  },
  {
    name: "Sweet Chilli Tuna Mayo Wrap",
    description: "Tuna with mayo & sweet chilli, leaf & Cucumber",
    pricePence: 360, category: "Seafood", menuCategory: "Specials",
    components: ["Tortilla Wrap", "Tuna", "Mayonnaise (egg powder recipe)", "Mixed Salad Leaf", "Sweet Chilli Sauce", "Cucumber"],
    nutrition: n(238, 996, 9.2, 1.7, 24, 3.7, 1.1, 11, 0.75),
  },
  {
    name: "Tomato and Basil Soup with White Bap and Butter",
    description: "Tomato and basil soup served with a white bap and butter portion",
    pricePence: null, category: "Vegetarian", menuCategory: "Specials",
    components: ["Tomatoes", "New Potatoes", "Vegetable Bouillon", "Fresh Basil", "White Roll", "Butter", "Salt & Black Pepper"],
    nutrition: null,
  },

  // ---------------- Rolls (rolls.pdf, 38 pages) ----------------
  {
    name: "Tuna Mayo and Cucumber in White Roll",
    description: "Tuna Mayo with Cucumber in a soft white roll",
    pricePence: null, category: "Seafood", menuCategory: "Rolls",
    components: ["White Roll", "Tuna", "Cucumber", "Mayonnaise", "Sunflower Spread", "Salt & Black Pepper"],
    nutrition: n(223, 935, 8, 0.9, 27, 2.3, 1.4, 11, 1.1),
  },
  {
    name: "Tuna Mayo & Cucumber on Sourdough",
    description: "Tuna Mayo with Cucumber in a crusty sourdough roll",
    pricePence: 435, category: "Seafood", menuCategory: "Rolls",
    components: ["Granary Roll", "Tuna", "Cucumber", "Mayonnaise", "Sunflower Spread", "Salt & Black Pepper"],
    nutrition: n(213, 898, 8.4, 1.3, 24, 1.8, 2.4, 12, 0.96),
  },
  {
    name: "Tuna Crunch Roll",
    description: "Tuna Mayo with crunchy mixed peppers in a malted wheat roll",
    pricePence: null, category: "Seafood", menuCategory: "Rolls",
    components: ["Malted Wheat Roll", "Tuna", "Mixed Peppers", "Mayonnaise"],
    nutrition: n(237, 995, 7.3, 0.9, 31, 1.7, 0.4, 11, 1.1),
  },
  {
    name: "Prawn Mayo and Leaf Roll",
    description: "Prawns in Mayonnaise with salad leaf in a malted wheat roll",
    pricePence: null, category: "Seafood", menuCategory: "Rolls",
    components: ["Malted Wheat Roll", "Prawns", "Mixed Salad Leaf", "Mayonnaise", "Sunflower Spread"],
    nutrition: n(225, 947, 7.3, 0.8, 31, 1.7, 0.4, 8.7, 1.3),
  },
  {
    name: "Ham, Cheddar & Pickle",
    description: "Ham and Mild Cheddar with Branston Pickle in a granary bap",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["Granary Bap", "Sliced Mild Cheddar", "Wafer Thin Ham", "Branston Original Pickle", "Sunflower Spread"],
    nutrition: n(244, 1026, 10, 4.7, 26, 5, 2.4, 13, 1.8),
  },
  {
    name: "Ham and Tomato in White Roll",
    description: "Wiltshire Ham with sliced Tomato in a soft white roll",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["White Roll", "Wiltshire Ham", "Tomatoes", "Sunflower Spread"],
    nutrition: n(219, 910, 15, 3.2, 14, 1.6, 1, 7.1, 1.1),
  },
  {
    name: "Ham & Salad Roll",
    description: "Wiltshire Ham with mixed salad leaf in a granary roll",
    pricePence: 190, category: "Red meat", menuCategory: "Rolls",
    components: ["Granary Roll", "Wiltshire Ham", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(105, 439, 5.6, 1.4, 2, 1.2, 0.4, 12, 1.3),
  },
  {
    name: "Ham & Pickle",
    description: "Ham with Branston Pickle in a soft white roll",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["White Roll", "Wafer Thin Ham", "Branston Original Pickle", "Sunflower Spread"],
    nutrition: n(217, 907, 6.3, 1.6, 32, 5.5, 0.4, 8.6, 1.1),
  },
  {
    name: "GLUTEN FREE Ham Roll",
    description: "Wiltshire Ham in a gluten free white roll",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["Gluten Free White Bread", "Wiltshire Ham", "Sunflower Spread"],
    nutrition: n(206, 864, 5.7, 1.1, 28, 1.2, 6, 7.8, 1.5),
  },
  {
    name: "GLUTEN FREE Cheese Roll",
    description: "Mature Cheddar in a gluten free white roll",
    pricePence: null, category: "Vegetarian", menuCategory: "Rolls",
    components: ["Gluten Free White Bread", "Mature Cheddar", "Sunflower Spread"],
    nutrition: n(302, 1261, 16, 8.1, 25, 0.9, 5.5, 11, 1.5),
  },
  {
    name: "Egg Mayo Roll",
    description: "Free range egg mayonnaise with cress in a granary roll",
    pricePence: null, category: "Vegetarian", menuCategory: "Rolls",
    components: ["Granary Roll", "Free Range Eggs", "Mayonnaise", "Sunflower Spread", "Cress", "Salt & Black Pepper"],
    nutrition: n(235, 989, 11, 2.2, 26, 1.7, 2.5, 11, 0.92),
  },
  {
    name: "Egg Mayo and Cress on White Roll",
    description: "Free range egg mayonnaise with cress in a soft white roll",
    pricePence: null, category: "Vegetarian", menuCategory: "Rolls",
    components: ["White Roll", "Free Range Eggs", "Mayonnaise", "Sunflower Spread", "Cress", "Salt & Black Pepper"],
    nutrition: n(244, 1020, 11, 1.8, 25, 2, 1.4, 7.8, 0.88),
  },
  {
    name: "Egg Mayo & Cress on Sourdough",
    description: "Free range egg mayonnaise with cress in a crusty sourdough roll",
    pricePence: 435, category: "Vegetarian", menuCategory: "Rolls",
    components: ["Granary Roll", "Free Range Eggs", "Mayonnaise", "Sunflower Spread", "Cress", "Salt & Black Pepper"],
    nutrition: n(233, 981, 11, 2.1, 25, 1.7, 2.5, 11, 0.91),
  },
  {
    name: "Egg & Bacon Roll",
    description: "Free range egg with streaky bacon in a malted wheat roll",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["Malted Wheat Roll", "Free Range Eggs", "Streaky Bacon", "Sunflower Spread"],
    nutrition: n(240, 1007, 8.4, 2.5, 29, 1.4, 0, 12, 1.5),
  },
  {
    name: "Coronation Chicken Roll",
    description: "Coronation Chicken in a soft white roll",
    pricePence: null, category: "Chicken", menuCategory: "Rolls",
    components: ["White Roll", "Coronation Chicken"],
    nutrition: n(249, 1037, 7.7, 1.2, 38, 4.1, 0.6, 8.2, 0.56),
  },
  {
    name: "Coronation Chicken on Sourdough",
    description: "Coronation Chicken in a crusty sourdough roll",
    pricePence: null, category: "Chicken", menuCategory: "Rolls",
    components: ["Sourdough Bap", "Coronation Chicken"],
    nutrition: n(231, 965, 6.3, 0.8, 35, 2.8, 0.4, 8.6, 0.97),
  },
  {
    name: "Chicken Mayo and Bacon Malted Roll",
    description: "Chicken Mayo with streaky bacon in a malted granary roll",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["Granary Roll", "Chicken Breast", "Mayonnaise", "Streaky Bacon", "Sunflower Spread"],
    nutrition: n(300, 1230, 15, 2.7, 24, 1.5, 2.1, 13, 1.4),
  },
  {
    name: "Chicken Mayo & Bacon White Roll",
    description: "Chicken Mayo with streaky bacon in a soft white roll",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["White Roll", "Chicken Breast", "Mayonnaise", "Streaky Bacon", "Sunflower Spread"],
    nutrition: n(295, 1214, 16, 2.5, 25, 2.1, 1.3, 10, 1.3),
  },
  {
    name: "Cheese Savoury on Granary Roll",
    description: "Mature Cheddar and Red Leicester with red and spring onion bound in mayonnaise",
    pricePence: null, category: "Vegetarian", menuCategory: "Rolls",
    components: ["Malted Wheat Roll", "Mature Cheddar", "Red Leicester", "Mayonnaise", "Red Onion", "Spring Onions", "Salt & Black Pepper"],
    nutrition: n(390, 1617, 35, 16, 1.9, 1.1, 0.4, 18, 1.6),
  },
  {
    name: "Cheese Sandwich",
    description: "Mature Cheddar on malted bread",
    pricePence: null, category: "Vegetarian", menuCategory: "Rolls",
    components: ["Malted Sandwich Bread", "Mature Cheddar", "Sunflower Spread"],
    nutrition: n(314, 1297, 14, 7.4, 33, 1.3, 2.3, 14, 1.2),
  },
  {
    name: "Cheese & Pickle Roll",
    description: "Mature Cheddar with Branston Pickle in a Soft White Roll",
    pricePence: null, category: "Vegetarian", menuCategory: "Rolls",
    components: ["White Roll", "Mature Cheddar", "Branston Original Pickle", "Sunflower Spread"],
    nutrition: n(285, 1199, 13, 6.9, 32, 5, 1.6, 13, 1.5),
  },
  {
    name: "Cheese & Pickle on Sourdough",
    description: "Mature Cheddar with Branston Pickle in a Sourdough Roll",
    pricePence: 190, category: "Vegetarian", menuCategory: "Rolls",
    components: ["White Roll", "Mature Cheddar", "Branston Original Pickle", "Sunflower Spread"],
    nutrition: n(321, 1336, 24, 14, 9.5, 8.4, 0.5, 16, 2.1),
  },
  {
    name: "BLT Roll",
    description: "Bacon, Lettuce, Tomato in a Soft White Roll",
    pricePence: null, category: "Red meat", menuCategory: "Rolls",
    components: ["White Roll", "Streaky Bacon", "Mixed Salad Leaf", "Tomatoes", "Butter"],
    nutrition: n(263, 1088, 22, 12, 10, 1.7, 0.7, 4.9, 0.83),
  },
  {
    name: "BBQ Pulled Pork",
    description: "BBQ Pulled Pork with Coleslaw and Leaf on a soft white roll",
    pricePence: 320, category: "Red meat", menuCategory: "Rolls",
    components: ["White Roll", "BBQ Pulled Pork", "Coleslaw", "Mixed Salad Leaf"],
    nutrition: n(229, 964, 7.1, 2.4, 33, 4.7, 1.8, 11, 1.1),
  },
  {
    name: "BBQ Chicken Mayo",
    description: "Chicken Mayo with Tangy BBQ Sauce on Soft White roll",
    pricePence: null, category: "Chicken", menuCategory: "Rolls",
    components: ["White Roll", "Chicken Breast", "Mayonnaise", "BBQ Sauce", "Sunflower Spread"],
    nutrition: n(285, 1183, 18, 3.3, 26, 7, 0.7, 5.2, 0.92),
  },
];
