// Eatpure sandwich catalogue, transcribed from the supplier's LabelLogic
// "Sandwiches Report" (05/07/2026) and the printed labels PDF. Nutrition is
// the supplier's finished-product panel per 100g: [kcal, kJ, fat, saturates,
// carbohydrate, sugars, fibre, protein, salt]; null where the source only had
// partial data (the label then omits the nutrition table). Recipe components
// are listed in the label's declaration order (heaviest first).

export type CatalogueProduct = {
  name: string;
  description: string | null;
  pricePence: number | null;
  category: "Red meat" | "Chicken" | "Vegetarian" | "Seafood";
  components: string[]; // names from import-eatpure-components, declaration order
  nutrition: [number, number, number, number, number, number, number, number, number] | null;
  packG: number | null;
};

const n = (
  kcal: number, kj: number, fat: number, sat: number, carb: number,
  sug: number, fib: number, prot: number, salt: number
): [number, number, number, number, number, number, number, number, number] =>
  [kcal, kj, fat, sat, carb, sug, fib, prot, salt];

export const CATALOGUE: CatalogueProduct[] = [
  {
    name: "All Day Breakfast on White Bread",
    description: "Cumberland Sausage, Streaky Bacon and Free Range Sliced Egg with tomato ketchup",
    pricePence: 380, category: "Red meat",
    components: ["White Bread", "Free Range Eggs", "Cumberland Sausage", "Streaky Bacon", "Tomato Ketchup", "Sunflower Spread"],
    nutrition: n(236, 989, 12, 3.8, 20, 2, 1.3, 14, 1.4), packG: 213,
  },
  {
    name: "Bacon Toastie",
    description: "Smoked streaky bacon to be toasted on white bloomer - ENJOY ME TOASTED!",
    pricePence: 520, category: "Red meat",
    components: ["White Bloomer", "Smoked Streaky Bacon"],
    nutrition: n(294, 1228, 13, 5.1, 30, 0.8, 1.9, 14, 1.4), packG: 150,
  },
  {
    name: "BLT Sandwich",
    description: "Bacon, Lettuce & Tomato on White Bread",
    pricePence: 370, category: "Red meat",
    components: ["White Bread", "Streaky Bacon", "Lettuce", "Tomatoes"],
    nutrition: n(227, 957, 9.2, 3, 25, 1.8, 1.6, 13, 1.8), packG: 160,
  },
  {
    name: "Brie, Bacon and Cranberry Panini",
    description: "Creamy Brie, with Bacon and Cranberry sauce - Enjoy me Toasted!",
    pricePence: 390, category: "Red meat",
    components: ["Panini", "Brie", "Streaky Bacon", "Cranberry Sauce"],
    nutrition: n(265, 1105, 10, 1.1, 34, 3.6, 1.8, 12, 1.3), packG: 205,
  },
  {
    name: "Baked Bean and Cheese Bloomer Toastie",
    description: "Baked Beans with Cheddar Cheese on White Bloomer - ENJOY ME TOASTED!",
    pricePence: 520, category: "Vegetarian",
    components: ["White Bloomer", "Baked Beans", "Sliced Mild Cheddar"],
    nutrition: null, packG: null,
  },
  {
    name: "BBQ Chicken & Leaf",
    description: "100% Chicken Breast with mayonnaise, BBQ Sauce and Leaf",
    pricePence: 260, category: "Chicken",
    components: ["Soft White Bread", "Chicken Breast", "Mayonnaise", "Mixed Salad Leaf", "BBQ Sauce", "Salt & Black Pepper"],
    nutrition: null, packG: null,
  },
  {
    name: "Brie & Cranberry with leaf on White Bloomer",
    description: "Creamy Brie & Cranberry with leaf on White Bloomer Bread",
    pricePence: 320, category: "Vegetarian",
    components: ["White Bloomer", "Brie", "Lettuce", "Cranberry Sauce", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Brioche Bacon Bap",
    description: "Cooked Bacon in a buttery Brioche Bun - ENJOY ME TOASTED!",
    pricePence: null, category: "Red meat",
    components: ["Brioche Bun", "Cooked Back Bacon", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Cheese & Onion Toastie",
    description: "Cheddar cheese with Red & Spring Onions on White Bloomer - ENJOY ME TOASTED!",
    pricePence: 520, category: "Vegetarian",
    components: ["White Bloomer", "Sliced Mild Cheddar", "Red Onion", "Spring Onions"],
    nutrition: n(251, 1052, 11, 6.2, 26, 1.3, 1.8, 13, 1.2), packG: 170,
  },
  {
    name: "Cheese & Branston Pickle White Bloomer",
    description: "Sliced Cheddar cheese & Branston Pickle on sliced bloomer",
    pricePence: null, category: "Vegetarian",
    components: ["White Bloomer", "Sliced Mild Cheddar", "Branston Original Pickle", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Cheese and Branston Pickle Malted Bloomer",
    description: "Cheddar cheese and Branston pickle on sliced malted bloomer",
    pricePence: null, category: "Vegetarian",
    components: ["Malted Bloomer", "Sliced Mild Cheddar", "Branston Original Pickle", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Emmental Cheese & Tomato Croissant",
    description: "Sliced Emmental Cheese with sliced tomato in a flaky butter Croissant",
    pricePence: null, category: "Vegetarian",
    components: ["All Butter Croissant", "Emmental", "Tomatoes"],
    nutrition: null, packG: null,
  },
  {
    name: "Cheese and Tomato Toastie",
    description: "Cheddar cheese with Beef Tomato on White Bloomer - ENJOY ME TOASTED!",
    pricePence: 520, category: "Vegetarian",
    components: ["White Bloomer", "Sliced Mild Cheddar", "Tomatoes"],
    nutrition: null, packG: null,
  },
  {
    name: "Cheese & Pickle Roll",
    description: "Mature Cheddar with Branston Pickle in a Soft White Roll",
    pricePence: 275, category: "Vegetarian",
    components: ["White Roll", "Mature Cheddar", "Branston Sweet Pickle", "Sunflower Spread"],
    nutrition: n(285, 1199, 13, 6.9, 32, 5, 1.6, 13, 1.5), packG: 138,
  },
  {
    name: "Cheese & Tomato Panini",
    description: "Mature Cheddar Cheese with Sliced Tomatoes",
    pricePence: 410, category: "Vegetarian",
    components: ["Panini", "Mature Cheddar", "Tomatoes"],
    nutrition: n(275, 1149, 10, 5.9, 36, 2.1, 2, 12, 1.3), packG: 185,
  },
  {
    name: "Cheese & Tomato, White Roll",
    description: "Sliced Cheddar with Tomato in a Soft White Roll",
    pricePence: 275, category: "Vegetarian",
    components: ["White Roll", "Mature Cheddar", "Tomatoes", "Sunflower Spread"],
    nutrition: n(281, 1179, 13, 7.1, 29, 1.8, 1.6, 13, 1.1), packG: 133,
  },
  {
    name: "Cheese Ploughman's White Bloomer",
    description: "Cheddar Cheese with Sweet Pickle, Mayo and salad in Soft White Bloomer",
    pricePence: 395, category: "Vegetarian",
    components: ["Strong White Bloomer", "Mature Cheddar", "Mayonnaise (egg powder recipe)", "Branston Sweet Pickle", "Sunflower Spread", "Cucumber", "Tomatoes", "Mixed Salad Leaf"],
    nutrition: n(288, 1199, 13, 5.6, 30, 2.1, 1.4, 12, 1.4), packG: 210,
  },
  {
    name: "Cheese Ploughman's on white",
    description: "Cheddar Cheese with Sweet Pickle, Mayo and salad on White Bread",
    pricePence: 340, category: "Vegetarian",
    components: ["Medium Sliced White Bread", "Mature Cheddar", "Mayonnaise (egg powder recipe)", "Branston Sweet Pickle", "Sunflower Spread", "Cucumber", "Tomatoes", "Mixed Salad Leaf"],
    nutrition: n(296, 1237, 15, 6.8, 25, 3.8, 1.8, 12, 1.2), packG: 190,
  },
  {
    name: "Cheese Roll",
    description: "Mature Cheddar in a Soft White Roll",
    pricePence: 275, category: "Vegetarian",
    components: ["White Roll", "Mature Cheddar", "Sunflower Spread"],
    nutrition: n(315, 1322, 15, 8, 33, 1.7, 1.7, 15, 1.3), packG: 118,
  },
  {
    name: "Cheddar Cheese Salad Bloomer",
    description: "Cheddar Cheese with salad on sliced bloomer",
    pricePence: null, category: "Vegetarian",
    components: ["Malted Bloomer", "Sliced Mild Cheddar", "Sliced Cooked Ham", "Cucumber", "Tomatoes", "Mixed Salad Leaf", "Sunflower Spread", "White Bloomer"],
    nutrition: null, packG: null,
  },
  {
    name: "Cheese Savoury on Malted Bread",
    description: "Cheese, mayo and red onion mix",
    pricePence: 370, category: "Vegetarian",
    components: ["Wholemeal Bread", "Mature Cheddar", "Red Leicester", "Mayonnaise", "Red Onion", "Spring Onions", "Low Fat Spread", "Salt & Black Pepper"],
    nutrition: n(300, 1255, 18, 7.8, 22, 1.9, 3.7, 13, 1.3), packG: 154,
  },
  {
    name: "Cheddar & Red Leicester Cheese Savoury on White Bloomer",
    description: "Cheese with Red Onion, Spring Onion and Mayonnaise",
    pricePence: null, category: "Vegetarian",
    components: ["White Bloomer", "Cheese Savoury Mix", "Spring Onions"],
    nutrition: null, packG: null,
  },
  {
    name: "Cheddar & Red Leicester Cheese Savoury on White Roll",
    description: "Cheese with Red Onion, Spring Onion and Mayonnaise",
    pricePence: 260, category: "Vegetarian",
    components: ["Soft White Bread", "Mature Cheddar", "Red Leicester", "Mayonnaise", "Low Fat Spread", "Red Onion", "Spring Onions", "Salt & Black Pepper"],
    nutrition: null, packG: null,
  },
  {
    name: "Chicken & Bacon Club",
    description: "Chicken Breast, Bacon, Lettuce & Tomato with Mayonnaise",
    pricePence: 325, category: "Red meat",
    components: ["Chicken Breast", "Wholemeal Bread", "Streaky Bacon", "Tomatoes", "Mixed Salad Leaf", "Mayonnaise", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Chicken & Bacon on Malted Bread",
    description: "Chicken breast and bacon with mayo",
    pricePence: 380, category: "Red meat",
    components: ["Wholemeal Bread", "Chicken Breast", "Streaky Bacon", "Mayonnaise", "Low Fat Spread", "Salt & Black Pepper"],
    nutrition: n(239, 1006, 11, 2.4, 19, 1.4, 3.2, 18, 2.1), packG: 180,
  },
  {
    name: "Chicken & Chorizo with Leaf on Malted Bloomer",
    description: "100% Chicken Breast, Chorizo, Leaf and Mayonnaise in a Malted Bloomer",
    pricePence: 320, category: "Red meat",
    components: ["Malted Bloomer", "Chicken Breast", "Mayonnaise", "Chorizo", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(273, 1146, 13, 2.3, 22, 1.4, 1.8, 16, 0.84), packG: 201,
  },
  {
    name: "Chicken & Sweetcorn",
    description: "100% Chicken Breast with mayonnaise and sweetcorn",
    pricePence: 370, category: "Chicken",
    components: ["White Bread", "Chicken Breast", "Mayonnaise", "Sweetcorn", "Salt & Black Pepper"],
    nutrition: n(213, 899, 7.7, 0.6, 24, 2.1, 1.7, 14, 1.2), packG: 175,
  },
  {
    name: "Chicken and Bacon Mayo on Malted Bloomer",
    description: "Chicken breast and bacon with mayo",
    pricePence: 440, category: "Red meat",
    components: ["Malted Bloomer", "Chicken Breast", "Streaky Bacon", "Mayonnaise", "Low Fat Spread", "Salt & Black Pepper"],
    nutrition: n(255, 1072, 9.4, 2.1, 24, 0.9, 2.2, 17, 1.9), packG: 200,
  },
  {
    name: "Chicken Caesar Salad Bowl",
    description: "Sliced Chicken on a bed of Cos Lettuce served with Italian Hard Cheese, Croutons, Cucumber and a Creamy Caesar dressing",
    pricePence: 480, category: "Chicken",
    components: ["Chicken Breast", "Lettuce", "Cucumber", "Mature Cheddar", "White Bread", "Caesar Dressing"],
    nutrition: n(125, 526, 5.1, 2.7, 5.3, 0.8, 0.7, 15, 0.35), packG: 255,
  },
  {
    name: "Chicken Caesar Wrap",
    description: "Chicken breast, Caesar dressing with leaf",
    pricePence: 440, category: "Chicken",
    components: ["Tortilla Wrap", "Chicken Breast", "Caesar Dressing", "Lettuce"],
    nutrition: n(181, 766, 3.4, 1.4, 28, 1.1, 2, 12, 1.3), packG: 180,
  },
  {
    name: "Chicken Mayo Roll",
    description: "Chicken Breast with Mayo in a soft white roll",
    pricePence: 295, category: "Chicken",
    components: ["White Roll", "Chicken Breast", "Mayonnaise", "Sunflower Spread", "Salt & Black Pepper"],
    nutrition: n(240, 1012, 8.3, 1.1, 30, 1.7, 1.6, 13, 1.2), packG: 133,
  },
  {
    name: "Diced Chicken Mayo on sliced Bloomer",
    description: "Diced Chicken Breast with Mayo on sliced Bloomer",
    pricePence: null, category: "Chicken",
    components: ["Malted Bloomer", "Chicken Breast", "Mayonnaise", "Sunflower Spread", "White Bloomer", "Salt & Black Pepper"],
    nutrition: null, packG: null,
  },
  {
    name: "Chicken Pesto on white bread",
    description: "Chicken with Pesto and Crunchy Spinach in White Bread",
    pricePence: 360, category: "Chicken",
    components: ["Medium Sliced White Bread", "Chicken Breast", "Green Pesto", "Baby Spinach", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Chicken Satay Wrap",
    description: "Sliced Chicken in a Satay Sauce with Crunchy Spinach - CONTAINS PEANUTS",
    pricePence: 440, category: "Chicken",
    components: ["Tortilla Wrap", "Chicken Breast", "Baby Spinach", "Satay Sauce"],
    nutrition: n(214, 901, 5.2, 1.8, 28, 2.9, 1.8, 13, 0.92), packG: 195,
  },
  {
    name: "Chicken Tikka with Iceberg Lettuce",
    description: "Chicken Tikka with Iceberg Lettuce",
    pricePence: 275, category: "Chicken",
    components: ["Soft White Bread", "Chicken Breast", "Mayonnaise", "Iceberg Lettuce", "Salt & Black Pepper"],
    nutrition: n(334, 1380, 31, 2, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Chicken, Chorizo & Cheese Panini",
    description: "100% Chicken breast, with slices of Chorizo and Mature Cheddar Cheese",
    pricePence: 450, category: "Chicken",
    components: ["Panini", "Chicken Breast", "Mature Cheddar", "Chorizo"],
    nutrition: n(255, 1064, 7.8, 4.4, 31, 1.7, 1.7, 17, 1.1), packG: 211,
  },
  {
    name: "Chunky Egg mayo with Cress on Malted Bread",
    description: "Chunky Egg Mayo with Cress on Malted Bread",
    pricePence: 370, category: "Vegetarian",
    components: ["Free Range Eggs", "Wholemeal Bread", "Mayonnaise", "Sunflower Spread", "Cress", "Salt & Black Pepper"],
    nutrition: n(226, 943, 14, 2.3, 16, 1.3, 2.7, 11, 0.8), packG: 122,
  },
  {
    name: "Coronation Chicken on White Roll",
    description: "Coronation chicken in a soft white roll",
    pricePence: 260, category: "Chicken",
    components: ["White Bread", "Chicken Breast", "Mayonnaise", "Curry Powder", "Raisins", "Low Fat Spread"],
    nutrition: n(299, 1252, 17, 2, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Coronation Chicken with leaf on white",
    description: "Coronation Chicken with leaf on white bread",
    pricePence: 360, category: "Chicken",
    components: ["Medium Sliced White Bread", "Coronation Chicken", "Lettuce", "Vegetable Spread", "Mixed Salad Leaf", "Sunflower Spread"],
    nutrition: n(223, 940, 6.2, 0.9, 33, 4.3, 2.2, 8.5, 0.74), packG: 160,
  },
  {
    name: "Coronation Chicken With Leaf on White Bloomer",
    description: "Coronation Chicken with leaf on White Bloomer",
    pricePence: 440, category: "Chicken",
    components: ["White Bloomer", "Coronation Chicken", "Lettuce", "Vegetable Spread"],
    nutrition: n(227, 951, 4.7, 0.4, 37, 3.6, 2.3, 9.5, 0.95), packG: 200,
  },
  {
    name: "Egg & Bacon on sliced Bloomer",
    description: "Sliced Egg & Streaky Bacon on sliced bloomer",
    pricePence: null, category: "Red meat",
    components: ["White Bloomer", "Free Range Eggs", "Streaky Bacon", "Sunflower Spread", "Malted Bloomer"],
    nutrition: n(227, 950, 9.5, 3, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Egg & Bacon Muffin",
    description: "Mini Omelette with streaky bacon in an English Muffin",
    pricePence: null, category: "Red meat",
    components: ["English Muffin", "Omelette", "Smoked Streaky Bacon"],
    nutrition: n(236, 988, 12, 4, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Egg Mayo & Cress Bloomer",
    description: "Chunky Egg mayo with cress on sliced bloomer",
    pricePence: null, category: "Vegetarian",
    components: ["White Bloomer", "Free Range Eggs", "Sunflower Spread", "Cress", "Mayonnaise", "Malted Bloomer", "Salt & Black Pepper"],
    nutrition: n(239, 994, 13, 2, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Eggs Benedict Muffin",
    description: "Egg, Spinach, Mozzarella with Hollandaise sauce",
    pricePence: null, category: "Vegetarian",
    components: ["English Muffin", "Omelette", "Mozzarella", "Baby Spinach", "Hollandaise Sauce"],
    nutrition: n(220, 925, 10, 4, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Egg Mayo & Cress in a soft Granary Roll",
    description: "Made with Free Range Eggs",
    pricePence: 285, category: "Vegetarian",
    components: ["Granary Roll", "Free Range Eggs", "Mayonnaise", "Sunflower Spread", "Cress", "Salt & Black Pepper"],
    nutrition: n(233, 981, 11, 2.1, 25, 1.7, 2.5, 11, 0.91), packG: 124,
  },
  {
    name: "Egg Mayo, Cress & Tomato Bloomer",
    description: "Egg Mayonnaise, Cress & Tomato on a Malted Bloomer",
    pricePence: 430, category: "Vegetarian",
    components: ["Malted Bloomer", "Free Range Eggs", "Tomatoes", "Mayonnaise", "Cress", "Salt & Black Pepper"],
    nutrition: n(219, 919, 8, 1.3, 26, 1.3, 2.3, 9.6, 0.68), packG: 190,
  },
  {
    name: "Falafel and Hummus Protein Salad Bowl",
    description: "Moroccan Falafel with Creamy Hummus, on a bed of crunchy Spinach, with Cherry Tomatoes, Olives, Cucumber and Red Onion, served with a side of Tzatziki",
    pricePence: 480, category: "Vegetarian",
    components: ["Moroccan Falafel", "Hummus", "Tzatziki", "Cucumber", "Baby Spinach", "Cherry Tomatoes", "Red Onion", "Black Olives"],
    nutrition: n(130, 546, 7.6, 1.2, 13, 6.6, 3.2, 3.9, 1.1), packG: 304,
  },
  {
    name: "Feta and Roast Red Pepper Pasta Salad Bowl",
    description: "Creamy Feta with Roast Red Peppers on a bed of Leaf topped with Spicy Arrabbiata Pasta",
    pricePence: 480, category: "Vegetarian",
    components: ["Feta", "Macaroni", "Roasted Red Peppers in Brine", "Arrabbiata Sauce", "Mixed Salad Leaf"],
    nutrition: n(202, 850, 7.2, 4.6, 25, 2, 1.5, 8.9, 1.1), packG: 245,
  },
  {
    name: "Gammon & Piccalilli",
    description: "Gammon Ham with tangy piccalilli, leaf and mayo on White Bread",
    pricePence: 300, category: "Red meat",
    components: ["White Bread", "Gammon Ham", "Mixed Salad Leaf", "Mayonnaise", "Tomato & Basil Sauce", "Sunflower Spread"],
    nutrition: n(212, 895, 7.9, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "GLUTEN FREE - Egg Mayo & Cress",
    description: "Egg Mayo & Cress on Gluten Free Bread",
    pricePence: 440, category: "Vegetarian",
    components: ["Gluten Free White Bread", "Free Range Eggs", "Mayonnaise", "Sunflower Spread", "Cress", "Salt & Black Pepper"],
    nutrition: n(235, 978, 12, 2.1, 22, 0.8, 4.6, 7.1, 1), packG: 168,
  },
  {
    name: "GLUTEN FREE - Tuna & Cucumber Sandwich",
    description: "Tuna Mayo with cucumber on Gluten Free Bread",
    pricePence: 440, category: "Seafood",
    components: ["Gluten Free White Bread", "Tuna", "Mayonnaise", "Cucumber", "Sunflower Spread"],
    nutrition: n(241, 1005, 13, 1.4, 20, 1, 4.3, 8.9, 0.91), packG: 164,
  },
  {
    name: "Vegan Cheese and Avocado Smash (Gluten Free)",
    description: "Vegan cheese with Seasoned Avocado Smash on GF bread",
    pricePence: null, category: "Vegetarian",
    components: ["Gluten Free White Bread", "Vegan Cheddar Slices", "Avocado", "Sunflower Spread"],
    nutrition: n(250, 1045, 12, 6, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "GLUTEN FREE/VEGAN - Falafel, Hummus, Sundried Tomato",
    description: "Falafel, Hummus and Sundried Tomato on Gluten Free Bread",
    pricePence: 325, category: "Vegetarian",
    components: ["Gluten Free White Bread", "Falafel", "Hummus", "Sundried Tomatoes", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Ham & Cheese Croissant",
    description: "Wiltshire Ham with sliced Emmental in a flaky buttery Croissant",
    pricePence: null, category: "Red meat",
    components: ["All Butter Croissant", "Sliced Cooked Ham", "Emmental"],
    nutrition: n(334, 1403, 18, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Ham & Cheese Panini",
    description: "Wiltshire Ham & Mature Cheddar - perfect toasted",
    pricePence: 450, category: "Red meat",
    components: ["Panini", "Wiltshire Ham", "Mature Cheddar"],
    nutrition: n(249, 1037, 8.1, 4.5, 32, 1.9, 1.8, 14, 1.5), packG: 205,
  },
  {
    name: "Ham & Cheese Roll",
    description: "Ham and Mature Cheddar in a Soft Granary Roll",
    pricePence: 290, category: "Red meat",
    components: ["Granary Roll", "Mature Cheddar", "Wiltshire Ham", "Sunflower Spread"],
    nutrition: n(251, 1059, 9.9, 4.8, 29, 2, 2.7, 14, 1.3), packG: 118,
  },
  {
    name: "Ham & Cheese Toastie",
    description: "Wiltshire Ham & Mature Cheddar - perfect toasted",
    pricePence: 380, category: "Red meat",
    components: ["White Bread", "Mature Cheddar", "Wiltshire Ham", "Sunflower Spread"],
    nutrition: n(263, 1101, 13, 7.2, 20, 1.5, 1.2, 16, 1.5), packG: 193,
  },
  {
    name: "Ham and Cheese Ciabatta",
    description: "Wiltshire Ham & Mature Cheddar with mustard mayo - perfect toasted",
    pricePence: 450, category: "Red meat",
    components: ["Ciabatta Roll", "Wiltshire Ham", "Mature Cheddar", "Mayonnaise", "Dijon Mustard"],
    nutrition: n(286, 1198, 14, 4.8, 25, 3.3, 2, 13, 1.3), packG: 225,
  },
  {
    name: "Ham Roll",
    description: "Slices of Ham in a Soft White Roll",
    pricePence: 275, category: "Red meat",
    components: ["White Roll", "Wiltshire Ham", "Sunflower Spread"],
    nutrition: n(220, 930, 4.3, 1, 36, 2.1, 1.8, 12, 1.3), packG: 108,
  },
  {
    name: "Ham Salad Bloomer",
    description: "Wiltshire Ham with salad on sliced bloomer",
    pricePence: null, category: "Red meat",
    components: ["Malted Bloomer", "Sliced Cooked Ham", "Cucumber", "Tomatoes", "Mixed Salad Leaf", "Sunflower Spread", "White Bloomer"],
    nutrition: n(168, 709, 3.4, 0, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Ham Salad on Malted Bread",
    description: "Honey Roast Ham, Leaf, Tomato & Cucumber",
    pricePence: 350, category: "Red meat",
    components: ["Wholemeal Bread", "Wiltshire Ham", "Mixed Salad Leaf", "Cucumber", "Tomatoes"],
    nutrition: n(154, 656, 2.4, 0.6, 24, 2.1, 4, 11, 1.1), packG: 142,
  },
  {
    name: "Ham, Cheese & Coleslaw on White",
    description: "Wiltshire Ham, Cheddar and Coleslaw on White Bread",
    pricePence: 360, category: "Red meat",
    components: ["Medium Sliced White Bread", "Wiltshire Ham", "Sliced Mild Cheddar", "Coleslaw", "Sunflower Spread"],
    nutrition: n(236, 992, 11, 4.6, 21, 2.5, 1.6, 13, 1.3), packG: 174,
  },
  {
    name: "Hunters Chicken Ciabatta",
    description: "Sliced Chicken and Bacon covered in Cheddar with a BBQ sauce",
    pricePence: 450, category: "Chicken",
    components: ["Ciabatta Roll", "Chicken Breast", "Mature Cheddar", "Streaky Bacon", "BBQ Sauce (smoky)"],
    nutrition: n(258, 1084, 11, 4.8, 23, 4.1, 1.6, 17, 1), packG: 260,
  },
  {
    name: "Luxury Smoked Salmon and Cream Cheese Bagel",
    description: "Smoked Atlantic Salmon with a thick layer of Cream Cheese",
    pricePence: 440, category: "Seafood",
    components: ["Plain Bagel", "Smoked Salmon", "Cream Cheese"],
    nutrition: n(253, 1072, 5.6, 1.4, 42, 3.7, 2.2, 12, 1.3), packG: 180,
  },
  {
    name: "Margherita Panini",
    description: "Panini with Tomato & Basil Sauce and Cheddar Cheese",
    pricePence: 410, category: "Vegetarian",
    components: ["Panini", "Mature Cheddar", "Tomato & Basil Sauce"],
    nutrition: n(284, 1184, 10, 6.1, 37, 2.1, 2, 13, 1.3), packG: 180,
  },
  {
    name: "Meatball and Cheese Baguette",
    description: "Sliced Meatballs in Tomato and Basil sauce with Cheddar Cheese",
    pricePence: 420, category: "Red meat",
    components: ["White Baguette", "Swedish Meatballs", "Sliced Mild Cheddar", "Tomato & Basil Sauce (chunky)"],
    nutrition: n(271, 1136, 13, 5, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Meatball Hot Wrap",
    description: "Sliced Meatballs in Tomato and Basil sauce with Cheddar Cheese",
    pricePence: 520, category: "Red meat",
    components: ["Tortilla Wrap", "Swedish Meatballs", "Sliced Mild Cheddar", "Tomato & Basil Sauce (chunky)"],
    nutrition: n(300, 1254, 17, 7, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Mixed Selection Chicken Sandwich Box",
    description: "Selection of Chicken sandwich quarters",
    pricePence: 375, category: "Red meat",
    components: ["Chicken Breast", "Wholemeal Bread", "White Bread", "BBQ Sauce", "Streaky Bacon", "Chorizo", "Tomatoes", "Lettuce", "Sunflower Spread", "Cucumber", "Mayonnaise", "Curry Powder"],
    nutrition: n(204, 862, 5.8, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Mozzarella & Pesto Wrap",
    description: "Mozzarella with Pesto, Sun dried Tomatoes, Leaf & Cucumber",
    pricePence: 360, category: "Vegetarian",
    components: ["Tortilla Wrap", "Grated Mozzarella & Cheddar", "Cucumber", "Mixed Salad Leaf", "Pesto alla Genovese", "Sundried Tomatoes"],
    nutrition: n(255, 1068, 13, 6, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "New York Deli Bagel",
    description: "Sliced Pastrami, Emmental cheese and crunchy gherkins covered with Mustard Mayo in a soft bagel - TRY ME TOASTED",
    pricePence: 430, category: "Red meat",
    components: ["Plain Bagel", "Pastrami", "Emmental", "Gherkins", "Mustard Mayonnaise"],
    nutrition: n(256, 1084, 7, 2.8, 38, 3.4, 2, 13, 1.4), packG: 180,
  },
  {
    name: "New York Deli Bloomer",
    description: "Pastrami, Emmental, Tomato, Gherkin and Mustard Mayo on White Bloomer",
    pricePence: 420, category: "Red meat",
    components: ["Strong White Bloomer", "Pastrami", "Mayonnaise", "Wholegrain Mustard", "Tomatoes", "Gherkins", "Sunflower Spread"],
    nutrition: n(236, 983, 11, 1.7, 24, 1.4, 1.2, 9.4, 1.4), packG: 260,
  },
  {
    name: "Onion Bhaji Wrap with Mango Chutney",
    description: "Onion Bhaji in Mango Chutney with Leaf - VEGAN FRIENDLY",
    pricePence: 480, category: "Vegetarian",
    components: ["Tortilla Wrap", "Onion Bhaji", "Mango Chutney", "Baby Spinach"],
    nutrition: n(239, 1004, 7.3, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Pepperoni Pizza HOT Wrap",
    description: "Sliced Pepperoni and Cheese with a tomato and Basil Sauce - Best Toasted",
    pricePence: 400, category: "Red meat",
    components: ["Tortilla Wrap", "Sliced Mild Cheddar", "Pepperoni", "Pizza Tomato & Basil Sauce"],
    nutrition: n(337, 1411, 19, 9, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Piri Piri Chicken with Mayo, Sweet Chilli, Tomato and Cucumber",
    description: "Piri Piri Chicken with Mayo, Sweet Chilli, Tomato and Cucumber",
    pricePence: 360, category: "Chicken",
    components: ["Malted Sandwich Bread", "Chicken Breast", "Mayonnaise (egg powder recipe)", "Tomatoes", "Sunflower Spread", "Piri-Piri Seasoning", "Sweet Chilli Sauce", "Cucumber"],
    nutrition: n(243, 1004, 8.7, 1.1, 25, 3.1, 2.3, 12, 1.1), packG: 175,
  },
  {
    name: "Piri Piri Chicken, Mayo and Leaf on Malted",
    description: "Piri Piri Chicken with Mayo and Leaf on Malted Bread",
    pricePence: 360, category: "Chicken",
    components: ["Malted Sandwich Bread", "Chicken Breast", "Mixed Salad Leaf", "Mayonnaise (egg powder recipe)", "Sunflower Spread", "Piri-Piri Seasoning"],
    nutrition: n(252, 1040, 9.2, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Piri Piri Chicken with Sweet Chilli sauce and Cheese Panini",
    description: "Piri Piri Chicken with Sweet Chilli sauce and Cheese in a Panini",
    pricePence: 450, category: "Chicken",
    components: ["Panini", "Mature Cheddar", "Chicken Breast", "Sweet Chilli Sauce", "Piri-Piri Seasoning"],
    nutrition: n(263, 1097, 9.2, 4.3, 32, 3.1, 2.1, 15, 1.4), packG: 219,
  },
  {
    name: "Plain Chicken Sandwich",
    description: "Sliced Chicken breast on white bread",
    pricePence: null, category: "Chicken",
    components: ["Medium Sliced White Bread", "Chicken Breast", "Sunflower Spread"],
    nutrition: null, packG: null,
  },
  {
    name: "Pork Gyros Wrap",
    description: "Pork Gyros with Creamy Tzatziki, Red Onion, Sliced Cucumber and Leaf",
    pricePence: 440, category: "Red meat",
    components: ["Tortilla Wrap", "Pork Gyros", "Cucumber", "Tzatziki", "Mixed Salad Leaf", "Red Onion"],
    nutrition: n(267, 1118, 13, 5.4, 28, 2.3, 1.4, 9.1, 0.91), packG: 200,
  },
  {
    name: "Prawn Mayo & Leaf Bloomer",
    description: "Prawns with Mayonnaise & Leaf on sliced Bloomer",
    pricePence: null, category: "Seafood",
    components: ["Malted Bloomer", "Prawns", "Mixed Salad Leaf", "Mayonnaise", "Sunflower Spread", "Salt & Black Pepper"],
    nutrition: n(227, 953, 8.4, 0, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Prawn Mayo with leaf on Malted Bread",
    description: "Creamy Prawn Mayonnaise with mixed leaf",
    pricePence: 390, category: "Seafood",
    components: ["Wholemeal Bread", "Prawns", "Mixed Salad Leaf", "Mayonnaise", "Low Fat Spread", "Salt & Black Pepper"],
    nutrition: n(195, 819, 7.9, 1, 23, 2, 4.9, 9.8, 1.1), packG: 154,
  },
  {
    name: "Red Pesto, Mozzarella, Sundried Tomato w/ basil Ciabatta",
    description: "Creamy Mozzarella with Red Pesto, Sundried tomatoes and basil - Perfect Toasted",
    pricePence: 450, category: "Vegetarian",
    components: ["Ciabatta Roll", "Mozzarella", "Sundried Tomatoes", "Red Pesto"],
    nutrition: n(237, 993, 9.4, 4.7, 27, 4, 2.2, 12, 0.61), packG: 235,
  },
  {
    name: "Roast Beef & Stilton",
    description: "Roast topside of beef with Stilton, caramelised onion & Rocket",
    pricePence: 380, category: "Red meat",
    components: ["Malted Bloomer", "Sliced Roast Beef", "Blue Stilton", "Caramelised Onion Chutney", "Sunflower Spread", "Rocket"],
    nutrition: n(239, 1005, 9.7, 4, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Sausage Toastie",
    description: "Sliced Cumberland Sausage to be toasted on white bloomer",
    pricePence: 520, category: "Red meat",
    components: ["White Bloomer", "Cumberland Sausage"],
    nutrition: n(243, 619, 8.3, 2, 32, 3.4, 1.9, 10, 1.2), packG: 160,
  },
  {
    name: "Sausage, Cheese and Caramelised Onion Toastie",
    description: "Sliced Cumberland Sausage, with Cheddar Cheese and Caramelised Onion Chutney to be toasted on white bloomer",
    pricePence: 520, category: "Red meat",
    components: ["White Bloomer", "Cumberland Sausage", "Sliced Mild Cheddar", "Onion Chutney (Brakes)"],
    nutrition: n(280, 877, 14, 6, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Sliced Egg Salad Bowl",
    description: "Served with mixed Salad, Cucumber, Carrot, Cherry Tomatoes and Sweetcorn and Coleslaw",
    pricePence: 480, category: "Vegetarian",
    components: ["Hardboiled Egg", "Cherry Tomatoes", "Coleslaw", "Mixed Salad Leaf", "Sweetcorn", "Carrot", "Cucumber"],
    nutrition: n(82, 342, 4.6, 1, 4.1, 2.5, 0.4, 6.3, 0.18), packG: 275,
  },
  {
    name: "Southern Fried Chicken and Bacon Hot Wrap",
    description: "Southern Fried Chicken Fillet, Bacon, Cheese & BBQ Sauce",
    pricePence: 450, category: "Chicken",
    components: ["Tortilla Wrap", "Southern Fried Chicken", "Mature Cheddar", "Streaky Bacon", "BBQ Sauce"],
    nutrition: n(295, 1235, 14, 7.2, 29, 2.5, 1.6, 14, 1.8), packG: 205,
  },
  {
    name: "Spicy Hummus and Asian Slaw Wrap",
    description: "Hummus with spicy Chipotle Sauce and Asian Slaw",
    pricePence: 395, category: "Vegetarian",
    components: ["Tortilla Wrap", "Carrot", "Red Cabbage", "Savoy Cabbage", "Hummus", "Mooli Radish", "Red Onion", "Chipotle Sauce"],
    nutrition: n(133, 560, 5, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Sweet Chilli Salmon Wrap",
    description: "Smashed Avocado, Sweet Chilli, Flaked Salmon, and Spinach",
    pricePence: 395, category: "Seafood",
    components: ["Fresh Salmon Fillet", "Avocado", "Baby Spinach", "Tortilla Wrap", "Asian Sweet Chilli Sauce"],
    nutrition: n(182, 760, 11, 2, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Sweet Chilli Chicken Wrap",
    description: "Chicken breast, sweet chilli dressing, leaf & cucumber",
    pricePence: 440, category: "Chicken",
    components: ["Tortilla Wrap", "Chicken Breast", "Cucumber", "Lettuce", "Sweet Chilli Dressing"],
    nutrition: n(179, 758, 3.3, 1.3, 26, 1.4, 2, 13, 1.4), packG: 110,
  },
  {
    name: "Tandoori Chicken with Iceberg Lettuce",
    description: "Tandoori Chicken with Iceberg Lettuce",
    pricePence: 275, category: "Chicken",
    components: ["Soft White Bread", "Chicken Breast", "Mayonnaise", "Iceberg Lettuce", "Salt & Black Pepper"],
    nutrition: null, packG: null,
  },
  {
    name: "Tuna Cheddar Toastie",
    description: "Tuna Mayo with spring onions and red peppers, covered in Sliced Cheddar on Malted Bloomer - Perfect Toasted",
    pricePence: 440, category: "Seafood",
    components: ["Malted Bloomer", "Tuna Mayonnaise", "Sliced Mild Cheddar", "Diced Red Peppers", "Spring Onions"],
    nutrition: n(252, 1058, 11, 5.1, 23, 1.1, 2.2, 14, 1.3), packG: 255,
  },
  {
    name: "Tuna & Cucumber Bloomer",
    description: "Tuna Mayonnaise with cucumber on sliced bloomer",
    pricePence: null, category: "Seafood",
    components: ["Malted Bloomer", "Tuna", "Cucumber", "Mayonnaise", "Sunflower Spread", "White Bloomer", "Salt & Black Pepper"],
    nutrition: n(230, 966, 10, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Tuna Crunch Bloomer",
    description: "Tuna Mayonnaise with peppers on sliced bloomer",
    pricePence: null, category: "Seafood",
    components: ["Malted Bloomer", "Tuna", "Mixed Peppers", "Sunflower Spread", "Mayonnaise", "White Bloomer", "Salt & Black Pepper"],
    nutrition: n(241, 1013, 9.4, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Tuna Crunch Wrap",
    description: "Tuna Mayo and Peppers with lettuce & Cucumber in a Wrap",
    pricePence: 440, category: "Seafood",
    components: ["Tortilla Wrap", "Tuna", "Mayonnaise", "Mixed Peppers", "Salt & Black Pepper"],
    nutrition: n(242, 1019, 9, 1.9, 30, 1.6, 2.1, 12, 1.2), packG: 162,
  },
  {
    name: "Tuna Mayo and Cucumber Roll",
    description: "Tuna Mayo with Cucumber in a Soft Granary Roll",
    pricePence: 285, category: "Seafood",
    components: ["Granary Roll", "Tuna", "Cucumber", "Mayonnaise", "Sunflower Spread", "Salt & Black Pepper"],
    nutrition: n(213, 898, 8.4, 1.3, 24, 1.8, 2.4, 12, 0.96), packG: 143,
  },
  {
    name: "Tuna Mayo on Malted Bread",
    description: "Tuna chunks with mayonnaise on Malted bread",
    pricePence: 260, category: "Seafood",
    components: ["Wholemeal Bread", "Tuna", "Mayonnaise", "Low Fat Spread", "Salt & Black Pepper"],
    nutrition: n(225, 945, 10, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Tuna Melt Ciabatta",
    description: "Tuna Mayonnaise & Mature Cheddar - ready for toasting",
    pricePence: 450, category: "Seafood",
    components: ["Ciabatta Roll", "Mature Cheddar", "Tuna", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(280, 1178, 12, 4.9, 27, 3.3, 2, 14, 0.88), packG: 205,
  },
  {
    name: "Tuna Melt Panini",
    description: "Tuna Mayonnaise & Mature Cheddar - ready for toasting",
    pricePence: 450, category: "Seafood",
    components: ["Panini", "Mature Cheddar", "Tuna", "Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(270, 1125, 11, 4.5, 31, 1.8, 1.7, 14, 1.3), packG: 210,
  },
  {
    name: "Tuna Sweetcorn on Malted Bread",
    description: "Tuna Mayo with Sweetcorn on Malted Bread",
    pricePence: 370, category: "Seafood",
    components: ["Wholemeal Bread", "Tuna", "Mayonnaise", "Sweetcorn", "Low Fat Spread", "Salt & Black Pepper"],
    nutrition: n(215, 905, 8.1, 1, 25, 2.2, 4.2, 12, 0.98), packG: 142,
  },
  {
    name: "Tuna with Vegan Mayo (No Butter)",
    description: "Tuna with Vegan Mayo - No Butter",
    pricePence: 360, category: "Seafood",
    components: ["Medium Sliced White Bread", "Tuna", "Vegan Mayonnaise", "Salt & Black Pepper"],
    nutrition: n(213, 898, 5.4, 0, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Ultimate Ploughman's",
    description: "Thick Ham and Sliced Cheddar with Mayo, Sweet Pickle and Salad on Soft White Bloomer",
    pricePence: 410, category: "Red meat",
    components: ["White Bloomer", "Wiltshire Ham", "Mature Cheddar", "Sunflower Spread", "Cucumber", "Tomatoes", "Mixed Salad Leaf", "Mayonnaise", "Branston Sweet Pickle"],
    nutrition: n(238, 995, 10, 4, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Falafel with Red Pepper Hummus, Beetroot falafel (VEGAN)",
    description: "Beetroot Falafel with Red Pepper Hummus, Tomato Chutney, Leaf & Cucumber",
    pricePence: 360, category: "Vegetarian",
    components: ["Tortilla Wrap", "Beetroot Falafel", "Red Pepper & Jalapeno Hummus", "Cucumber", "Mixed Salad Leaf", "Spicy Tomato Chutney"],
    nutrition: n(184, 774, 6.8, 1, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Vegan Cheese and Avocado Smash",
    description: "Vegan cheese with Seasoned Avocado Smash on White bread",
    pricePence: 360, category: "Vegetarian",
    components: ["Medium Sliced White Bread", "Vegan Cheddar Slices", "Avocado", "Sunflower Spread"],
    nutrition: n(261, 1095, 13, 7, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Vegan Cheese and Tomato with Vegan Mayo Sandwich on White",
    description: "Vegan Cheese and Tomato with Vegan Mayo Sandwich on White",
    pricePence: 360, category: "Vegetarian",
    components: ["Medium Sliced White Bread", "Vegan Cheddar Slices", "Tomatoes", "Vegan Mayo (Lion)"],
    nutrition: n(273, 1141, 14, 7.2, 31, 2.5, 2, 5.2, 1), packG: 145,
  },
  {
    name: "Vegan Cheese with Vegan Mayo",
    description: "Vegan Cheese with Vegan Mayo",
    pricePence: 360, category: "Vegetarian",
    components: ["Medium Sliced White Bread", "Vegan Cheddar Slices", "Vegan Mayo (Lion)"],
    nutrition: n(292, 1220, 15, 7, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Vegan Festive New Yorker",
    description: "Vegan cheese, pickled red cabbage, Mustard mayo & Festive chutney on Malted Bloomer",
    pricePence: 380, category: "Vegetarian",
    components: ["Malted Bloomer", "Vegan Slice (Kerrymaid)", "Real Ale Chutney", "Pickled Red Cabbage", "Sunflower Spread", "Vegan Mayo (Lion)", "English Mustard"],
    nutrition: n(251, 1053, 12, 5, 0, 0, 0, 0, 0), packG: null,
  },
  {
    name: "Vegan Ham Sandwich",
    description: "Vegan Ham on White Bread",
    pricePence: null, category: "Vegetarian",
    components: ["Medium Sliced White Bread", "Vegan Ham", "Sunflower Spread"],
    nutrition: n(213, 898, 4.6, 1, 0, 0, 0, 0, 0), packG: null,
  },
];
